### PR TITLE
Update Windows setup with Python version recommendations

### PR DESCRIPTION
**Pull request by Matthew-Jennings**
Add python 3.10 warning.
Remove references to Anaconda
Update links

### CODE REVIEW

**Review by SimonBiggs — APPROVED** [review]
And last time I had access to Windows to build the docs I needed Python 3.7 ... Not sure if that's the case still...

(Feel free to merge after I approve btw :) )

**Comment by Matthew-Jennings** [comment]
> And last time I had access to Windows to build the docs I needed Python 3.7 ... Not sure if that's the case still...
> 
> (Feel free to merge after I approve btw :) )

I managed to build docs locally using Python 3.9.13 :)

**Comment by SimonBiggs** [comment]
> I managed to build docs locally using Python 3.9.13 :)

Woohoo :) glad to hear it. Thanks for all this maintenance work by the way @Matthew-Jennings, it has been sorely needed 🙂

**Comment by Matthew-Jennings** [comment]
> > I managed to build docs locally using Python 3.9.13 :)
> 
> Woohoo :) glad to hear it. Thanks for all this maintenance work by the way @Matthew-Jennings, it has been sorely needed 🙂

Pleasure :)

**Pull request merged**
