### PR TITLE
Added plan complexity code to labs

### PR DESCRIPTION
**Pull request by db72-git**
I have added the code I have written for calculating a couple of plan complexity metrics to the labs as discussed via email a couple of weeks ago.

### CODE REVIEW

**Comment by SimonBiggs** [comment]
Heya @db72-git,

There are still a few steps left:

* Fixing any continuous integration (CI) errors (described below)
* Undergoing a code review
* Optionally including your name and logo within the readme (https://github.com/pymedphys/pymedphys/blob/master/README.rst)

Before we get to the code review it's worth having all the ducks in a row for the CI. Whenever code is submitted to PyMedPhys a [continuous integration](https://www.atlassian.com/continuous-delivery/continuous-integration) server spins up. It goes off and tests a range of things, and one of these is pylint: 

https://github.com/pymedphys/pymedphys/pull/880/checks?check_run_id=776223920#step:29:313

If you have set up the dev install environment [as per the docs](https://docs.pymedphys.com/howto/advanced/setup-win.html) you should be able to run the following within the git repo:

```
poetry run pymedphys dev tests --pylint
```

That will then tell you locally if you have any pylint issues.

I personally use the [VSCode editor](https://code.visualstudio.com/) and this repo has some things set up within it that will make it so that VSCode will inform you in your file (a bit like a spell checker) if there are any pylint issues.

We can move on to the review step once we've fixed up pylint and have green ticks on all the CI tasks:

image

Cheers,
Simon

**Comment by db72-git** [comment]
Thanks for all the help, sorry it's taking so long!

I have just loaded my code up into VSCode and according to this there are about 300 pylint syntax issues that need to be fixed. Mostly things like trailing whitespaces and unused imports. Also I seem to be getting conflicting objections to naming convention (some don't conform to snake_case, some don't conform to UPPER_CASE etc.). I have generally been using camelCase however have probably been mixing between more than one which I am now discovering is 'bad practice' so should probably go through and rename all the variables to the same format and be a bit more careful in future. Looks like snake_case seems to be the one we use for pymedphys things??

As there are so many changes, is it easier to squash this request and do a new one or is it fine to just commit a bunch more changes and swap all the docs over?

**Comment by SimonBiggs** [comment]
Hi David,

It's all good to keep this pull request, I don't mind lots of commits, go
to town. No need to stress about time taken, all good.

We could also do a merge of this one as is if you'd like, just make sure to
include `# pylint: skip-file` at the top. With respect to code style I aim
to follow the Google style guide document --
http://google.github.io/styleguide/pyguide.html

It's a nice read and it helps make code that's nice to read :).

While we're at it, the following documents are also great:

https://github.com/google/eng-practices

**Comment by SimonBiggs** [comment]
Also, the following guide might be helpful:

https://github.com/pymedphys/pymedphys/issues/893

**Comment by db72-git** [comment]
Not sure what's going on here will sit and go through all this stuff properly at the weekend. Think i am screwing up the pre-commit thing? My work PC is throwing up a lot of proxy errors when trying to do some of the dev environment stuff so will see if i get more luck trying at at home

**Comment by SimonBiggs** [comment]
Heya @db72-git,

Can I dive in and fix this one? And can we work within the plan-complexity branch of pymedphys? I'll make a new PR.

**Pull request merged**
