### PR TITLE
[0] Put out fire

### PR DESCRIPTION
**Pull request by SimonBiggs**
Given the nature of this one here, I'm going to need to be "making a stack :/"

### CODE REVIEW

**Comment by sjswerdloff** [comment]
Might this have something to do with my social fork breaking when I synch'd a little while ago (today)?

**Comment by SimonBiggs** [comment]
> Might this have something to do with my social fork breaking when I synch'd a little while ago (today)?

Yup :)

**Review by sjswerdloff — APPROVED** [review]
Although the proof is in the pudding

**Comment by SimonBiggs** [comment]
😄 

image

-- https://xkcd.com/1739/

**Pull request merged**
