### PR TITLE
[RFR] add logo

### PR DESCRIPTION
**Pull request by SimonBiggs**
@Centrus007 what do you think?

https://github.com/pymedphys/pymedphys/blob/logo-iteration/notebooks/logo/logo.svg

### CODE REVIEW

**Comment by SimonBiggs** [comment]
Logo turned into favicons for each OS.

[favicon_package_v0.16.zip](https://github.com/pymedphys/pymedphys/files/3051503/favicon_package_v0.16.zip)

**Comment by SimonBiggs** [comment]
@Centrus007 what do you think about the two following, which one do you prefer?

image

image

**Comment by Centrus007** [comment]
Why not match the blue and yellow of Python?

Python logo

Pandas logo

NumPy logo

![PyDicom logo]https://pydicom.github.io/pydicom/stable/_static/pydicom_flat_black.svg)

**Comment by Centrus007** [comment]
Otherwise, very nice!!!

**Comment by Centrus007** [comment]
I don't suppose we can lengthen the tail for a bit more left/right symmetry? :p

**Comment by SimonBiggs** [comment]
Yes, I like it. Those colours will be quite perfect I think. And yup, tail lengthening coming up :)

**Pull request merged**
