### PR TITLE
Add immutables

### PR DESCRIPTION
**Pull request by SimonBiggs**

### CODE REVIEW

**Review by sjswerdloff — APPROVED** [review]

**Comment by SimonBiggs** [comment]
Needed to run `poetry update`, running that now

**Review by sjswerdloff — APPROVED** [review]
was this updated poetry.lock driven by a run of propagate-extras.py or was it due to an update to pyproject.toml that didn't get followed by poetry update ?
There's a fair amount of magic involved, so it's good to know which incantations are needed and when...

**Comment by SimonBiggs** [comment]
Yeah, it was me running `propagate-extras.py` but not following that with a `poetry update`. That way when the doctest ran the equivalent of `pip install pymedphys[user]` it didn't actually install immuatbles. Doctest shouldn't actually need immutables though. I really should just tell it to ignore that `_imports.imports.py` file.

**Comment by SimonBiggs** [comment]
Yeah, there is quite a bit of magic in `poetry`. But it is certainly worth the trade off. `propagate-extras.py` however... that I need to make a bit cleaner.

**Pull request merged**
