### PR TITLE
Bring back quickcheck

### PR DESCRIPTION
**Pull request by SimonBiggs**
Thanks @ayalalazaro for the this (https://github.com/pymedphys/pymedphys/issues/1794#issuecomment-1519638796)

Here is a PR pulling the code back in.

The commands run to bring back quickcheck were:

```
git checkout 3e45a8510ec3d4d20195c5c5447d0618e2d0d7b4 -- lib/pymedphys/_experimental/quickcheck
git checkout 3e45a8510ec3d4d20195c5c5447d0618e2d0d7b4 -- lib/pymedphys/tests/experimental/quickcheck
git checkout 3e45a8510ec3d4d20195c5c5447d0618e2d0d7b4 -- lib/pymedphys/experimental/__init__.py
git checkout 3e45a8510ec3d4d20195c5c5447d0618e2d0d7b4 -- lib/pymedphys/experimental/quickcheck.py
```

Please let me know if I missed anything :slightly_smiling_face: 

---

To run the tests for quickcheck I did the following:

```
poetry run pymedphys dev tests -k quickcheck
```

Which got the following output:

```
Running pytest with cwd set to:
    /home/simon/git/pymedphys/lib/pymedphys

Test session starts (platform: linux, Python 3.11.3, pytest 7.3.1, pytest-sugar 0.9.7)
rootdir: /home/simon/git/pymedphys/lib/pymedphys
plugins: sugar-0.9.7, hypothesis-5.49.0, rerunfailures-11.1.2
collected 163 items / 160 deselected / 3 selected                                                                                                                        

 tests/experimental/quickcheck/test_quickcheck.py ✓                                                                                                         33% ███▍      

―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― TestQcMethods.test_get_measurements ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

self = <pymedphys.tests.experimental.quickcheck.test_quickcheck.TestQcMethods testMethod=test_get_measurements>, socket_send = <function _socket_send at 0x7f32bde5a480>

    def test_get_measurements(self, socket_send):
        """Tests measurements retrieval, checks shape of the measurements pandas dataframe and specific
        values of the data"""
        qc = QuickCheck("127.0.0.1")
        socket_send.side_effect = mock_socket_send
        qc.connect()
>       qc.get_measurements()

tests/experimental/quickcheck/test_quickcheck.py:68: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
_experimental/quickcheck/qcheck.py:219: in get_measurements
    m = self._parse_measurements()
_experimental/quickcheck/qcheck.py:207: in _parse_measurements
    m[data_split[0]] = np.int(data_split[1:][0])
_vendor/apipkg/__init__.py:238: in __getattribute__
    return getattr(getmod(), name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

attr = 'int'

    def __getattr__(attr):
        # Warn for expired attributes, and return a dummy function
        # that always raises an exception.
        import warnings
        try:
            msg = __expired_functions__[attr]
        except KeyError:
            pass
        else:
            warnings.warn(msg, DeprecationWarning, stacklevel=2)
    
            def _expired(*args, **kwds):
                raise RuntimeError(msg)
    
            return _expired
    
        # Emit warnings for deprecated attributes
        try:
            val, msg = __deprecated_attrs__[attr]
        except KeyError:
            pass
        else:
            warnings.warn(msg, DeprecationWarning, stacklevel=2)
            return val
    
        if attr in __future_scalars__:
            # And future warnings for those that will change, but also give
            # the AttributeError
            warnings.warn(
                f"In the future `np.{attr}` will be defined as the "
                "corresponding NumPy scalar.", FutureWarning, stacklevel=2)
    
        if attr in __former_attrs__:
>           raise AttributeError(__former_attrs__[attr])
E           AttributeError: module 'numpy' has no attribute 'int'.
E           `np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
E           The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
E               https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

/home/simon/.cache/pypoetry/virtualenvs/pymedphys-OJ9w3Q6B-py3.11/lib/python3.11/site-packages/numpy/__init__.py:305: AttributeError
-------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------
UDP target IP: 127.0.0.1
UDP target port: 8123
Connected to Quickcheck
SER;1000

 tests/experimental/quickcheck/test_quickcheck.py ⨯✓                                                                                                       100% ██████████
======================================================================== short test summary info =========================================================================
FAILED tests/experimental/quickcheck/test_quickcheck.py::TestQcMethods::test_get_measurements - AttributeError: module 'numpy' has no attribute 'int'.

Results (1.97s):
       2 passed
       1 failed
         - tests/experimental/quickcheck/test_quickcheck.py:62 TestQcMethods.test_get_measurements
     160 deselected

```

### CODE REVIEW

**Comment by ayalalazaro** [comment]
I replaced np.float with float and np.int with int.  I hope everything is OK. Thanks for your help!

**Comment by SimonBiggs** [comment]
> I replaced np.float with float and np.int with int. I hope everything is OK. Thanks for your help!

Looks great :) thanks @ayalalazaro 🙏

**Comment by SimonBiggs** [comment]
@Matthew-Jennings, are you happy to review and merge this one?

The actual changes from the original code are within the following:

https://github.com/pymedphys/pymedphys/pull/1801/commits/44652c181cb3780c8f0709f4800a9affbf5e6482

**Review by Matthew-Jennings — APPROVED** [review]
LGTM :)

**Comment by SimonBiggs** [comment]
Thanks @Matthew-Jennings :slightly_smiling_face:

**Pull request merged**
