### PR TITLE
Docs automated tests

### LINKED ISSUE #1717: Document "Automated Tests"
> ... @SimonBiggs I see that most of the contributions in lib\pymedphys\tests came from you and other past contributors... I can try having a look at the tests, but I think it will require time and guidance.

_Originally posted by @nlambriICH in https://github.com/pymedphys/pymedphys/issues/1701#issuecomment-1195115931_

Referring to the review checklist:

>  Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

https://github.com/openjournals/joss-reviews/issues/4555#issuecomment-1187692538

### PR DESCRIPTION
**Pull request by nlambriICH**
Closes #1717

### CODE REVIEW

**Review by SimonBiggs — APPROVED** [review]
Looks great to me! :slightly_smiling_face:

**Comment by SimonBiggs** [comment]
We need to pull the updates test out into their own workflow so that a failing updates test doesn't cause all of the other tests to cancel...

image

**Comment by nlambriICH** [comment]
I need some guidance for that.

Should I change the library.yml or add a new workflow [here](https://github.com/pymedphys/pymedphys/actions)? Could you point me to some useful docs?

**Comment by SimonBiggs** [comment]
Oh, we don't have to do that for this PR. You can give it a shot if you like. I'm happy to merge this one with those tests failing due to that.

To fix it, the updates tests need to be moved into a different workflow. I'm happy to take that one...

**Pull request merged**
