### PR TITLE
Fix broken anon docs link

### LINKED ISSUE #1650: Anonymisation link broken within the docs
image

-- https://docs.pymedphys.com/lib/ref/dicom.html

https://github.com/pymedphys/pymedphys/blob/f7251729b5d6655e7930854a0e558a195688025a/lib/pymedphys/_dicom/anonymise/api.py#L42

### PR DESCRIPTION
**Pull request by Matthew-Jennings**
Closes #1650

Merging into Python 3.10 branch for now (I need to work from that branch locally to build the docs). Can instead merge into main if preferred.

### CODE REVIEW

**Comment by SimonBiggs** [comment]
Would we be able to instead use sphinx's relative documentation links combined with the following extension?

https://pypi.org/project/sphinx-jsonschema/

**Comment by Matthew-Jennings** [comment]
> Would we be able to instead use sphinx's relative documentation links combined with the following extension?
> 
> https://pypi.org/project/sphinx-jsonschema/
> 
> That way sphinx will handle pulling the json file in directly, and any move of documents in the future won't break it again...

I can try, but it's not clear to me exactly how to use the relative link functionality of `sphinx-jsonschema` from within a docstring as in [pymedphys/lib/pymedphys/_dicom/anonymise/api.py](https://github.com/pymedphys/pymedphys/blob/f7251729b5d6655e7930854a0e558a195688025a/lib/pymedphys/_dicom/anonymise/api.py#L42).

Plus, as I understand it, moving `identifying_keywords.json` would break a relative link just as easily as a weblink, right?

**Comment by SimonBiggs** [comment]
> EDIT: you're suggesting a move of the entire `docs` folder, not just `identifying_keywords.json`. Fair enough. Still, this will take me a bit longer.

:+1:

**Comment by Matthew-Jennings** [comment]
I'm sorry, I think this is beyond my ability to efficiently solve independently.

**Comment by SimonBiggs** [comment]
> I'm sorry, I think this is beyond my ability to efficiently solve independently.

Well certainly don't close it :slightly_smiling_face:. Using the following guide:

**In general, reviewers should favor approving a CL once it is in a state where
it definitely improves the overall
code health of the system
being worked on, even if the CL isn't perfect.**

https://github.com/google/eng-practices/blob/716687a5444960dd21ab84185de2228bb8ad1652/review/reviewer/standard.md?plain=1#L31-L34

This PR is certainly an improvement over the previous state.

**Review by SimonBiggs — APPROVED** [review]

**Pull request merged**
