### PR TITLE
[RFR] Netlify docs

### PR DESCRIPTION
**Pull request by SimonBiggs**
Here are the docs built with netlify, using yarn:

https://staging.pymedphys.com

This means, once we remove readthedocs we can pour all of our install resources into using yarn, and make that be "the one way" instead of needing requirements files.

I'll likely just be merging this one in so that I can keep iterating, attempting to make multiple version deploys.

### CODE REVIEW

**Comment by SimonBiggs** [comment]
Sorry for the force pull on this one. Nature of using branches to build docs, I kinda need it merged to keep working on it ...

**Comment by Centrus007** [comment]
All good :)

**Comment by SimonBiggs** [comment]
@Centrus007 by the way, the documentation preview built automatically for every pull request is awesome :). You just need to click "details" next to the following item:

image

**Comment by Centrus007** [comment]
Yep, i noticed that! Very cool :D

**Pull request merged**
