### PR TITLE
show explicit VR failure

### PR DESCRIPTION
**Pull request by SimonBiggs**

### CODE REVIEW

**Comment by SimonBiggs** [comment]
@mrbean-bremen, not sure if this is of interest to you, but setting `dataset.is_implicit_VR = False` causes everything to explode. :).

**Comment by mrbean-bremen** [comment]
This is odd - do you some binary compare of the datasets? I may have a look later tonight.

**Comment by SimonBiggs** [comment]
Yup, I'll write up a minimum working example.

**Comment by SimonBiggs** [comment]
> This is odd - do you do some binary compare of the datasets? I may have a look later tonight.

Yup, here, below is a minimal working example:

```python
[simon@study-pc pymedphys]$ ipython
Python 3.7.5 (default, Dec 19 2019, 21:33:42) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.9.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import io 
   ...:  
   ...: import pydicom 
   ...:  
   ...: from pymedphys._dicom import create                                     

In [2]: dataset = create.dicom_dataset_from_dict( 
   ...:     { 
   ...:         "BeamSequence": [ 
   ...:             {"TreatmentMachineName": "hello"}, 
   ...:             {"TreatmentMachineName": "george"}, 
   ...:         ] 
   ...:     } 
   ...: ) 
   ...:  
   ...: dataset.is_little_endian = True                                         

In [3]: dataset.is_implicit_VR = True 
   ...: implicit_vr = io.BytesIO() 
   ...: dataset.save_as(implicit_vr) 
   ...:  
   ...: implicit_vr.seek(0) 
   ...: implicit_vr.read()                                                      
Out[3]: b'\n0\xb0\x00,\x00\x00\x00\xfe\xff\x00\xe0\x0e\x00\x00\x00\n0\xb2\x00\x06\x00\x00\x00hello \xfe\xff\x00\xe0\x0e\x00\x00\x00\n0\xb2\x00\x06\x00\x00\x00george'

In [4]: dataset.is_implicit_VR = False 
   ...: explicit_vr = io.BytesIO() 
   ...: dataset.save_as(explicit_vr) 
   ...:  
   ...: explicit_vr.seek(0) 
   ...: explicit_vr.read()                                                      
Out[4]: b'\n0\xb0\x00SQ\x00\x00,\x00\x00\x00\xfe\xff\x00\xe0\x0e\x00\x00\x00\n0\xb2\x00SH\x06\x00hello \xfe\xff\x00\xe0\x0e\x00\x00\x00\n0\xb2\x00SH\x06\x00george'

In [5]: implicit_file_dataset = pydicom.read_file(implicit_vr, force=True) 
   ...: explicit_file_dataset = pydicom.read_file(explicit_vr, force=True)      

In [6]: implicit_file_dataset                                                   
Out[6]: 
(300a, 00b0)  Beam Sequence   2 item(s) ---- 
   (300a, 00b2) Treatment Machine Name              SH: 'hello'
   ---------
   (300a, 00b2) Treatment Machine Name              SH: 'george'
   ---------

In [7]: explicit_file_dataset                                                   
Out[7]: Expected sequence item with tag (fffe, e000) at file position 0x10

(0a30, b000)     1 item(s) ---- 
   (0a30, b200)                                     SH: 'hello þÿ\x00à\x0e\x00\x00\x00\n0²\x00SH\x06\x00george'
   ---------
```

**Comment by SimonBiggs** [comment]
@mrbean-bremen see the following notebook, if that helps:

https://github.com/pymedphys/pymedphys/blob/827d5962e141897506105e9e6305dcac6d14db9d/examples/github-issue-responses/implicit_vs_explicit_vr.ipynb

**Comment by mrbean-bremen** [comment]
The explanation of the problem is over [at pydicom](https://github.com/pydicom/pydicom/issues/1062#issuecomment-593137564). As I see it, it is not a real bug, as it cannot happen in real datasets, but meanwhile you probably have to stay with the implicit transfer syntax as a default for your tests.

**Comment by SimonBiggs** [comment]
> The explanation of the problem is over [at pydicom](https://github.com/pydicom/pydicom/issues/1062#issuecomment-593137564). As I see it, it is not a real bug, as it cannot happen in real datasets, but meanwhile you probably have to stay with the implicit transfer syntax as a default for your tests.

Yup, I'm more than happy whatever you decide. Thank you :), appreciate your time on this.

Cheers,
Simon

**Pull request closed without merging**
