### PR TITLE
Upgrade streamlit

### PR DESCRIPTION
**Pull request by SimonBiggs**
This involves an update to Streamlit from version `0.82.0` --> `1.2.0`. In the process I removed an experimental app called "Extend CT". This removal was due to that application using some private Streamlit APIs that now no longer exist as previous.

I'll make a note in the change log that this was removed, and if someone would like it back again it'd be great if they could jump in and update the application to no longer use those private APIs.

### CODE REVIEW

**Comment by SimonBiggs** [comment]
@rembishj if you have the bandwidth it might be worth checking to make sure your Streamlit applications haven't been broken by this Streamlit update (given we don't have any automated tests to check to make sure your work isn't broken).

Up to you though :slightly_smiling_face:.

**Review by pchlap — APPROVED** [review]
This all looks fine to my @SimonBiggs. I'm not a Streamlit expert but this all seems reasonable so I will leave my approval here for you to proceed when you're ready.

**Comment by SimonBiggs** [comment]
Thanks @pchlap,

I'll merge this in so that it's ready for tomorrow morning.

**Comment by rembishj** [comment]
> @rembishj if you have the bandwidth it might be worth checking to make sure your Streamlit applications haven't been broken by this Streamlit update (given we don't have any automated tests to check to make sure your work isn't broken).
> 
> Up to you though 🙂.

@SimonBiggs Unfortunately I haven't really been able to keep working on this now that I have started at NYU and we rely on ARIA. :/

I will get in touch with Chris and have him try updating and seeing if things broke there.

**Comment by SimonBiggs** [comment]
Hi Jake,

It's all good :). How are you?

**Pull request merged**
