### PR TITLE
added references regarding in-house development in JOSS paper

### PR DESCRIPTION
**Pull request by guanfada**
@SimonBiggs
I have added references regarding in-house development in JOSS paper per the reviewer's request.
Please check.
Thx.

### CODE REVIEW

**Comment by SimonBiggs** [comment]
The paper CI is failing. I would recommend pulling your branch locally and making sure you can build the paper.

**Comment by guanfada** [comment]
@SimonBiggs I forgot how to build the paper.

**Comment by SimonBiggs** [comment]
> @SimonBiggs I forgot how to build the paper.

See the following:

https://joss.readthedocs.io/en/latest/submitting.html#docker

**Comment by guanfada** [comment]
@SimonBiggs I overlooked an comma in paper.bib. It's fixed now, and I just successfully generated the paper.pdf file.
https://github.com/pymedphys/pymedphys/actions/runs/2945583195

**Comment by guanfada** [comment]
@SimonBiggs can you take a look at the paper.pdf and merge this PR?

**Review by sjswerdloff — APPROVED** [review]
The results LGTM.
The only part that worries me is that there is a pre commit failure.
The MacOS time out failures seem irrelevant.

**Comment by SimonBiggs** [comment]
@guanfada would you be able to follow the instructions over at your other PR to fix the pre-commit failures?

https://github.com/pymedphys/pymedphys/pull/1700#issuecomment-1204800471

Cheers,
Simon

**Comment by guanfada** [comment]
@SimonBiggs I followed all the steps. And I can see "passed" for all when I used pre-commit on my cmd. 
poetry run pre-commit run --all-files

image

but pre-commit still failed on the webpage.

**Comment by guanfada** [comment]
@SimonBiggs 

image

**Comment by SimonBiggs** [comment]
> I worked on my guanfada-patch-1

Is your local version of `guanfada-patch-1` up to date with what is within your online branch? Would you be able to run `git pull`

**Comment by SimonBiggs** [comment]
Thanks @sjswerdloff :slightly_smiling_face: 

> The results LGTM.
> The only part that worries me is that there is a pre commit failure.

Yup, that's enough not to merge (would be very painful having all pre-commits fail in main...)

> The MacOS time out failures seem irrelevant.

Yeah... that's due to the updates test failing. We need to make sure that "required" tests do not depend on "nice-to-have" tests. See the following:

https://github.com/pymedphys/pymedphys/issues/1726

**Comment by guanfada** [comment]
> 

yes, my local computer's version is same as the online guanfada-patch-1, and yes, I can git pull, but it shows Already up to date.
I tried again, and my local computer has all passed, but the online pre-commit failed, as before.

**Comment by SimonBiggs** [comment]
Ah yes... it's because you're using a fork. I'll merge this... and we need to make this easier for you :)

One option, if you'd like, you can make branches directly on the PyMedPhys repo itself? I believe I have already given you the required permission to be able to do that...

**Comment by guanfada** [comment]
> Ah yes... it's because you're using a fork. I'll merge this... and we need to make this easier for you :)
> 
> One option, if you'd like, you can make branches directly on the PyMedPhys repo itself? I believe I have already given you the required permission to be able to do that...

@SimonBiggs sound good to me :-)

**Comment by SimonBiggs** [comment]
@guanfada, unfortunately the test is actually failing within main:

image

Would you be open to making a branch within the PyMedPhys repo (as opposed to your own fork) and run pre-commit, and see if you can get the CI to pass?

**Comment by guanfada** [comment]
@SimonBiggs I just made a guanfada-patch-2 based on pymedphys main. I will do pre-commit then.

**Comment by SimonBiggs** [comment]
> @SimonBiggs I just made a guanfada-patch-2 based on pymedphys main. I will do pre-commit then.

Thanks @guanfada :slightly_smiling_face:

**Comment by guanfada** [comment]
@SimonBiggs Do I need to open a new PR? or I can just operate on my local cmd?

**Comment by SimonBiggs** [comment]
You'll need to do a `git push` and then make a PR from that branch:

image

image

**Comment by SimonBiggs** [comment]
I'm hoping once we get past some of these teething issues these process will be a lot smoother :slightly_smiling_face:

**Comment by guanfada** [comment]
@SimonBiggs 
image

**Comment by SimonBiggs** [comment]
You need a git pull first. And you need to make sure that origin is set to https://github.com/pymedphys/pymedphys/ (or the ssh equivalent) when you run `git remote -v`

**Comment by guanfada** [comment]
@SimonBiggs 
image

image

**Comment by guanfada** [comment]
@SimonBiggs 
image
It's really frustrating. Nothing worked.

**Comment by guanfada** [comment]
I feel like I am still working on guanfada/pymedphys in cmd, rather than pymedphys/pymedphys.

**Comment by SimonBiggs** [comment]
Might we be able to organise a video call to solve this?

**Comment by guanfada** [comment]
@SimonBiggs I just emailed you a zoom invitation.

**Pull request merged**
