### PR TITLE
[STACK base] Fix imports being complained about by pylint, pin hypothesis

### PR DESCRIPTION
**Pull request by SimonBiggs**
... and move the imports to a more sensible location anyway.

See https://github.com/pymedphys/pymedphys/issues/1305 for more details.

### CODE REVIEW

**Comment by SimonBiggs** [comment]
@Matthew-Jennings might you be in the position for a fly-by-code-review? 🙂

**Comment by SimonBiggs** [comment]
@pchlap might you be in a position to do a few code reviews?

**Comment by pchlap** [comment]
> @pchlap might you be in a position to do a few code reviews?

Can do @SimonBiggs, however it probably won't be until later in the week if thats ok?

**Comment by SimonBiggs** [comment]
> > @pchlap might you be in a position to do a few code reviews?
> 
> Can do @SimonBiggs, however it probably won't be until later in the week if thats ok?

Yup, all good 🙂

**Review by sjswerdloff — APPROVED** [review]

**Comment by SimonBiggs** [comment]
Thanks @sjswerdloff for doing those. Appreciated 😄 

@pchlap thanks for the offer for jumping in, can I take you up on it another week in cases where @sjswerdloff is swamped?

**Comment by pchlap** [comment]
> Thanks @sjswerdloff for doing those. Appreciated 😄
> 
> @pchlap thanks for the offer for jumping in, can I take you up on it another week in cases where @sjswerdloff is swamped?

That suits me just fine @SimonBiggs  :)

**Pull request merged**
