### PR TITLE
Add the linac state code 16, correct the meanning of code 34

### PR DESCRIPTION
**Pull request by daliDuans**
I  add the linac state code 16, and correct the meanning of code 34 in the "pymedphys/lib/pymedphys/_trf/decode/config.json". Please review it. Thank you!
The meanning of codes 16  and 34 were given in the following figure, which was obtained from Elekta linac engineer.
状态编码1

### CODE REVIEW

**Comment by sjswerdloff** [comment]
There was a specific test failure that suggests a test update might be needed.

FAILED tests/trf/test_decode.py::test_conversions - AssertionError: 
Arrays are not equal
The Linac State/Actual Value (None) column should be equal
Mismatched elements: 1 / 1105 (0.0905%)
 x: array(['Intersegment', 'Intersegment', 'Intersegment', ...,
       'Terminated Ok', 'Terminated Ok', 'State Code Unknown'],

**Comment by daliDuans** [comment]
Can you help do that?



---Original---
From: ***@***.***&gt;
Date: Sat, Mar 16, 2024 08:27 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pymedphys/pymedphys] Add the linac state code 16, correct themeanning of code 34 (PR #1827)




 
There was a specific test failure that suggests a test update might be needed.
 
FAILED tests/trf/test_decode.py::test_conversions - AssertionError:
 Arrays are not equal
 The Linac State/Actual Value (None) column should be equal
 Mismatched elements: 1 / 1105 (0.0905%)
 x: array(['Intersegment', 'Intersegment', 'Intersegment', ...,
 'Terminated Ok', 'Terminated Ok', 'State Code Unknown'],

**Comment by sjswerdloff** [comment]
See #1822 for the reason for this PR.
I updated the PR with a commit that reverted the value of 34, which was what caused the automated tests to fail.
There are a set of tests that have the CSV conversion from existing TRF files which contained the current value for 34.
I also altered the value for linac state code 16 to simplify it to Closed.
If there is a need to modify the value for linac state code 34, *all* of the baseline samples must be updated using the updated version for the linac state code (i.e. if you want to change a "value" for a linac state code, part of the PR has to include a complete update of the CSV conversions of the sample/regression test data).
To fully meet testing requirements, the sample TRF that contained a linac state code of 16 should be added to the set of test data (and the converted _header.csv and _table.csv).
However, a TRF sample file was included in #1822 and local testing was successful in conversion where the last row contained the mapped value for the linac state code 16 ("Closed"):
97.68	14410	33920	242	0	19	5	**Closed**	0	91.1	5831	0	Out	29	-0.2	0	0	-75	0	206.1	0	-249.8	0	185	0	145.5	144.5	0	0	116.3	50	-0.2	0	1	1	5.4	4.9	4.5	3.9	3.4	2.9	2.5	4.4	4.2	4.1	9.9	14	15.4	15.7	16.6	20.1	25.2	31.4	41.5	63.6	71.1	75.9	74.3	59.8	84.1	84.1	98.1	76.1	97	98.4	100.5	102.8	105.5	106.6	111.1	110.7	110.8	111.8	111.9	111.3	111.4	111.7	113.8	114	114.2	114.1	112.6	114	113.3	112.7	115.2	115.7	115.7	115.1	115.1	114.8	114.7	114.8	114.3	114.5	114.4	114.5	114.4	113.2	114.1	111.9	110.2	109.5	103.9	94.7	93	95.3	92.8	2.8	3.2	3.8	4.2	4.8	5.2	5.7	5.6	5.2	4.7	4.2	3.8	3.3	2.8	-0.2	-0.2	-0.5	-3.3	-1.5	2.8	-5	-6	-7.1	-9.3	-10.1	-12.8	-32.6	-35.3	-36.8	-37.1	-10	-41.6	-46.2	-60.8	-38.5	-50.3	-58.5	-60.8	-60	-63.3	-60.7	-74.4	-68.4	-69.3	-68.2	-69.8	-65.9	-67.1	-70.1	-74.7	-78.3	-78.5	-76.9	-75.9	-73.4	-84.5	-84.9	-86	-77.6	-77.9	-76.5	-78.2	-79.1	-80.4	-80.1	-80.9	-82.7	-84.3	-85	-85.4	-85.2	-85	-81.4	-88.4	-85.9	-97.5	-84.4	-89.2	-91.5	-88.1	2.9	3.3	3.7	4.3	4.8	5.3	5.8	-0.1	-0.1	0	-0.1	-0.2	-0.2	-0.1	-0.2	-0.1	-0.2	-0.1	-0.1	-0.1	-0.1	-0.1	-0.1	-0.1	-0.1	-0.1	-0.1	-0.1	-0.1	-0.1	-0.1	-0.1	-0.1	-0.1	-0.1	0	-0.1	-0.1	0	-0.1	0	0	-0.1	-0.1	-0.1	-0.1	-0.1	-0.1	0	0	0	0	-0.1	-0.1	-0.1	0	0	0	-0.1	-0.1	-0.1	0	0	0	0	-0.1	0.1	0	0	0	0	0.1	0	0	0	0	0	0	0	0	0	0	0.1	0.1	0.1	0.1	0.1	-0.2	-0.2	-0.2	-0.2	-0.2	-0.2	-0.1	-0.2	-0.2	-0.2	-0.1	-0.1	-0.1	-0.2	-0.1	-0.2	-0.1	-0.2	-0.2	-0.2	-0.2	-0.2	-0.3	-0.3	-0.2	-0.2	-0.1	-0.1	-0.2	-0.1	-0.1	-0.2	-0.1	-0.2	-0.1	-0.1	-0.2	-0.1	-0.2	-0.2	-0.1	-0.2	-0.1	-0.1	-0.2	-0.1	-0.2	-0.2	-0.1	-0.1	-0.2	-0.1	-0.2	-0.1	-0.2	-0.1	-0.1	-0.2	-0.1	-0.1	-0.1	-0.2	-0.1	-0.2	-0.1	-0.2	-0.1	-0.1	-0.2	-0.1	-0.1	-0.2	-0.1	-0.1	-0.1	0	-0.1	-0.1	-0.2	-0.2

**Comment by sjswerdloff** [comment]
@SimonBiggs if you are satisfied without requiring an update to the test data (that would provide proof that the fix works for linac state code 16), then please review/approve, and I can merge (or you can).  Adding to the test data will require a few extra steps (downloading from zenodo, appending to the zip, uploading to zenodo, updating the urls.json to point to the new version on zenodo) that I've run out of time for this weekend.

**Comment by SimonBiggs** [comment]
Hi Stuart :), happy for you to be autonomous here and make the call either way

**Review by SimonBiggs — APPROVED** [review]

**Comment by daliDuans** [comment]
Dear SimonBiggs, i apologize for my lack of familiarity with Python. Could you please guide me on how to install the updated code on my computer? Should I use the command "pip install pymedphys[user]" to reinstall it? Thank you! @SimonBiggs

**Comment by SimonBiggs** [comment]
A new release should be landing soon, so hopefully you'll be able to use that when it lands

**Comment by SimonBiggs** [comment]
Actually, it's available now. Try version 0.40.0 :)

**Comment by daliDuans** [comment]
Thank you very much! The TRF file that previously failed to convert was successfully converted to a CSV file using the new version 0.40.0.

**Comment by SimonBiggs** [comment]
Congrats on your first PR to PyMedPhys! :) If you'd be keen you could even make another PR adding yourself as an active contributor, and if you're looking for a next potential task, we are always keen to have people with fresh eyes be able to grow, expand, and refine our docs!

https://docs.pymedphys.com/

**Pull request merged**
