### PR TITLE
0.39.3 release prep

### PR DESCRIPTION
**Pull request by Matthew-Jennings**

### CODE REVIEW

**Review by SimonBiggs — APPROVED** [review]
LGTM :)

**Comment by Matthew-Jennings** [comment]
@SimonBiggs, sorry to be a pain, but how did you edit the Zenodo archive as per JOSS requirements for 0.39.2?

I want to do it for 0.39.3 but still cannot see how to do so.

**Comment by SimonBiggs** [comment]
Unfortunately, there is no way at the moment to share Zenodo permissions :(. The workaround would be to create a shared account (yuck).

...I'm going to have to do it I believe :(

**Comment by Matthew-Jennings** [comment]
@SimonBiggs, would you mind please making those edits at your earliest convenience? I'm mindful of keeping our editors waiting.

**Comment by SimonBiggs** [comment]
> @SimonBiggs, would you mind please making those edits at your earliest convenience? I'm mindful of keeping our editors waiting.

It's going to have to wait a little longer.

**Pull request merged**
