### PR TITLE
Revert "Merge pull request #1534 from pymedphys/unexpose-pseudonymise"

### PR DESCRIPTION
**Pull request by sjswerdloff**
This reverts commit 72f5e72316b7761527757b5a53fd7eeadd5dcdcb, reversing
changes made to 9b16b9cbc293276422e7209c658160962405fba9.

### CODE REVIEW

**Comment by SimonBiggs** [comment]
Yup, if this is a straight reversal, and it passes the tests, it has my approval :).

**Comment by sjswerdloff** [comment]
> Yup, if this is a straight reversal, and it passes the tests, it has my approval :).

I had to resolve a conflict in the __init__.py file by deleting a warning line from the "unexpose".
Otherwise it was pure automated revert

**Comment by sjswerdloff** [comment]
not sure why the ,updates is failing...

**Review by SimonBiggs — APPROVED** [review]

**Comment by SimonBiggs** [comment]
> not sure why the ,updates is failing...

Yup, that's separated out because rarely it has anything to do with the current PR. But is still something that needs to have tabs kept on. Potentially in the future it could be a test that we only run on master after a merge. It doesn't really need to add noise or CI time to the PR itself...

**Pull request merged**
