### PR TITLE
[RFR] PyMedPhys docs restyle + addition of supporter pages

### PR DESCRIPTION
**Pull request by SimonBiggs**

### CODE REVIEW

**Comment by Centrus007** [comment]
Looking very nice! Maybe a slight color difference between the sidebar and main section?

**Comment by SimonBiggs** [comment]
@Centrus007 keen for your review on this one. I didn't just retheme, but I also added a placeholder advertisement. There are also a few extra sections under a new heading "supporters"

**Comment by SimonBiggs** [comment]
Since the page is loading faster on netlify I seem to be getting a flash of unstyled content. The readthedocs theme seems to put scripts before CSS. If I swap that round that should fix the flash.

Also, the wording of those new supporter sections really needs a bit of work. If you have any ideas on how to say it better, please go to town.

**Comment by SimonBiggs** [comment]
Alright @Centrus007 :) this is ready for review :).

I made a slight change to the nav bar colour, plus a heap of other stuff.

**Comment by SimonBiggs** [comment]
The flash of unstyled content appears fixed by appropriately organising the CSS and JavaScript within the layout template.

**Comment by Centrus007** [comment]
LGTM :D

**Comment by SimonBiggs** [comment]
Awesome :) thanks Matt :)

**Pull request merged**
