### PR TITLE
[RFR] Edit logos

### PR DESCRIPTION
**Pull request by SimonBiggs**
@kingrpaul @peterg1t @Centrus007 would you each be able to check the logos section 
of https://deploy-preview-391--docs-pymedphys.netlify.com/#our-team

I have shrunk each logo just to its emblem and made them take up a 200x200 px spacing. Given that I am editing your logos I wanted to get your approval before I merge this one in.

Cheers,
Simon

### CODE REVIEW

**Comment by SimonBiggs** [comment]
> Looks good. Thanks.

Thanks @kingrpaul :)

**Comment by Centrus007** [comment]
Happy mate :)

**Comment by SimonBiggs** [comment]
@msobolewski for your reference, here is the discussion regarding the logos. Just awaiting approval from @peterg1t and then approval internally and it should be okay to continue with the logo adjustments.

**Comment by SimonBiggs** [comment]
@pchlap if you wanted to add a 200x200 px logo like these ones done in this pull request that'd be great. Probably best to just merge into this pull request, I still need approval on my end for my logo mangling :).

**Comment by pchlap** [comment]
> @pchlap if you wanted to add a 200x200 px logo like these ones done in this pull request that'd be great. Probably best to just merge into this pull request, I still need approval on my end for my logo mangling :).

I was looking at adding a logo, but UNSW seems really uptight about where and how their logo may be used. So I think I will avoid adding one for the time being until I clarify if/how I am allowed to use it.

**Comment by SimonBiggs** [comment]
> I was looking at adding a logo, but UNSW seems really uptight about where and how their logo may be used. So I think I will avoid adding one for the time being until I clarify if/how I am allowed to use it.

Good plan :)

**Pull request merged**
