### PR TITLE
add Claude Assistant

### PR DESCRIPTION
**Pull request by Matthew-Jennings**
I'm testing a new GitHub Action that calls you. Hope to hear from you!

### CODE REVIEW

**Comment by Matthew-Jennings** [comment]
@claude test

**Comment by SimonBiggs** [comment]
Oh @claude that is painful 😞. Are enough people doing it that it's making you want to change your username?

**Comment by claude** [comment]
not enough to change my username, but definitely annoying ;)

**Comment by Matthew-Jennings** [comment]
Apologies, that was a silly oversight on my part.

**Pull request closed without merging**
