### PR TITLE
Fix test failures

### PR DESCRIPTION
**Pull request by Matthew-Jennings**

### CODE REVIEW

**Comment by Matthew-Jennings** [comment]
@SimonBiggs, it looks like [this datafile link](https://github.com/pymedphys/pymedphys/blob/7ebae3a7d3d31fc2be952801edd4137871e3be93/lib/pymedphys/_data/urls.json#L34) has broken without any new commits to `pymedphys`. They were originally added in [this commit](https://github.com/pymedphys/pymedphys/commit/2ff82336ef28b1f3442467bedd09e5c926aaf062)

The location differs from all other data file locations in [urls.json](https://github.com/pymedphys/pymedphys/blob/main/lib/pymedphys/_data/urls.json), so I'm not entirely sure how to fix, sorry!

**Comment by SimonBiggs** [comment]
Oh that sucks, given the name I believe it refers to this issue number:
https://github.com/pymedphys/pymedphys/issues/1047

And probably this comment here:
https://github.com/pymedphys/pymedphys/issues/1047#issuecomment-691389682

With this download URL:
https://github.com/pymedphys/pymedphys/files/5212087/NPCA_Anonymised.zip

**Comment by Matthew-Jennings** [comment]
> Oh that sucks, given the name I believe it refers to this issue number: #1047
> 
> And probably this comment here: [#1047 (comment)](https://github.com/pymedphys/pymedphys/issues/1047#issuecomment-691389682)
> 
> With this download URL: https://github.com/pymedphys/pymedphys/files/5212087/NPCA_Anonymised.zip
> 
> Maybe the file needs to be downloaded from there and then re-upped to zenodo?

I could've sworn that link didn't work yesterday....

Happy to download, upload to Zenodo and update the link! Shall I add it to an existing dataset or add a new one? I'm not sure I have sufficient access to most of them to post new versions.

**Comment by SimonBiggs** [comment]
Really doesn't matter where you upload it :) Just somewhere we trust

**Comment by Matthew-Jennings** [comment]
@SimonBiggs, `test_icom_cli` seems to only be obtaining ~160 of the expected 255 files: https://github.com/pymedphys/pymedphys/actions/runs/8277205136/job/22654250284?pr=1826#step:29:210

I did dive a little deeper, but really not sure what's going on here. Completely unfamiliar with the `icom` stuff.

**Comment by laser47-hue** [comment]
@Matthew-Jennings, with regards to the test_icom_cli it looks like the test icom listener is being terminated immediately after the data has finished sending from the mock icom server, which means there is not enough time for the byte stream to be saved to txt files and stored in a temp directory. An easy slightly ugly fix, but i think robust enough is to put a time.sleep(1) between icom_server_process.join() and icom_listen_cli.terminate() in the pymedphys/tests/icom/test_icom_cli.py file line 47 and 48.

**Comment by SimonBiggs** [comment]
Thanks @laser47-hue!! @Matthew-Jennings, I believe @laser47-hue has fixed this issue over in https://github.com/pymedphys/pymedphys/pull/1828#pullrequestreview-1940959050 which is now merged.

**Comment by sjswerdloff** [comment]
@SimonBiggs the tests passed, I'm not sure if this is "luck" or by modifying and kicking off a fresh CI that the fix from @laser47-hue got incorporated (having been merged in to main).
If you approve I can merge (it may not merge without conflict resolution, I had some issues getting it to merge in my local environment).

**Comment by sjswerdloff** [comment]
@SimonBiggs @Matthew-Jennings @pchlap the pyright tests, which are not required, are consistently failing (with a lot of failures).  I installed NodeJS 20 and npm 10 in my local environment, and they found even more to complain about (about twice as many failures) as Node 14.
Do we want to leave these tests running all the time and ignore until we can do something about it (is there a separate issue for this?), or should we turn the tests off in the CI workflow, and just run it on local environments (and have a handful of separate issues and perhaps try to break it down in to smaller pieces)?
I don't see a reason to hold back on the 0.40 release for lack of meeting all of the type checking expectations of pyright.

**Review by sjswerdloff — APPROVED** [review]
LGTM

**Comment by SimonBiggs** [comment]
Yup, don't hold back the release for pyright. That would definitely be the tail wagging the dog

**Pull request merged**
