### PR TITLE
[RFR] 0.8.x

### PR DESCRIPTION
**Pull request by SimonBiggs**
I have made a set of release candidates. We should install these and play with them a bit. See if everything works. Then I think we should forge a release (that way we can begin playing with the files within pyodide...)

### CODE REVIEW

**Comment by SimonBiggs** [comment]
This depends was based on top of https://github.com/pymedphys/pymedphys/pull/283

**Comment by SimonBiggs** [comment]
Actually, I think it's worth making a full 0.8.0 release. We won't be releasing it on conda for a while, but getting a full release out in on pypi will be worthwhile.

**Comment by SimonBiggs** [comment]
Let's just merge this in within https://github.com/pymedphys/pymedphys/pull/285

**Comment by Centrus007** [comment]
I'm having trouble following, sorry. Do you still want to release 0.8.0? Should this be closed?

**Comment by SimonBiggs** [comment]
@Centrus007 all good. No need to merge this though.

**Pull request closed without merging**
