### PR TITLE
Add gui for pseudonymisation

### PR DESCRIPTION
**Pull request by SimonBiggs**
See parent PR for details https://github.com/pymedphys/pymedphys/pull/1100.

**Todo:**

* [x] Make CI boot pseudonymise server for testing (@SimonBiggs)
* [x] Use in memory DICOM file storage instead of a potentially write protected directory
* [x] Make the Cypress tests pass when called via `poetry run pymedphys dev tests --run-only-yarn`

**Can be done within another PR if so desired:**

* [ ] Within testing download the GUI pseudonymised files and verify they results agree with what would have occured with the CLI
  * An option to make the code easier to write and read would be to do file comparison within a python script called by cypress with an eval command.

### CODE REVIEW

**Comment by SimonBiggs** [comment]
Hi @sjswerdloff,

So I have made it so that streamlit appropriately boots the server for pseudonymise. You can now run exactly what the CI server will be running locally by calling the following in this new branch:

```bash
poetry run pymedphys dev tests -v -s --run-only-yarn
```

If you want it to run a little quicker I would recommend running:

```bash
poetry run pymedphys dev tests -v -s -x --run-only-yarn
```

As that will make it so that after the first run, it will no longer run the mudensity e2e tests while the pseudonymise tests are failing.

With this extra tooling, are you in a position to take another look at the cypress test, and see if you can get it to pass locally using the above command?

If there are files that you need downloaded for the tests to run, can you have them be downloaded within the following function:

https://github.com/pymedphys/pymedphys/blob/06d31b6c6e4a8063868c7437aa9a4653448014d3/pymedphys/tests/e2e/test_cypress.py#L57

See an example at:

https://github.com/pymedphys/pymedphys/blob/06d31b6c6e4a8063868c7437aa9a4653448014d3/pymedphys/tests/e2e/test_cypress.py#L43

Also, can I recommend, to stop the intermittent failing of cypress, to use the "streamlit waiting" tooling that I have created:

* go to the url and wait for the streamlit app to be ready before testing -- https://github.com/pymedphys/pymedphys/blob/d15464aef5924357ef975a7adb9ec62d771de36e/pymedphys/tests/e2e/cypress/integration/streamlit/mudensity-compare.js#L5
* wait for a computation to finish -- https://github.com/pymedphys/pymedphys/blob/d15464aef5924357ef975a7adb9ec62d771de36e/pymedphys/tests/e2e/cypress/integration/streamlit/mudensity-compare.js#L8

Essentially, you need to write `cy.start()` at the beginning of a test, and then you need to write `cy.compute()` after you expect the Python code to be doing something in response to a GUI interaction.

See the following for where I have defined these two functions:

https://github.com/pymedphys/pymedphys/blob/d15464aef5924357ef975a7adb9ec62d771de36e/pymedphys/tests/e2e/cypress/support/commands.js#L28-L37

https://github.com/pymedphys/pymedphys/blob/d15464aef5924357ef975a7adb9ec62d771de36e/pymedphys/tests/e2e/cypress/support/commands.js#L51-L55

**Comment by SimonBiggs** [comment]
Of note, if you want to see the video for the running of the Cypress tests see:

```
pymedphys/pymedphys/tests/e2e/cypress/videos/streamlit/pseudonymisation.spec.js.mp4
```

**Comment by SimonBiggs** [comment]
To help diagnose e2e GUI testing issues within the CI server I have also made it so that should the cypress test fail it will upload the videos as artefacts within GitHub Actions:

https://github.com/pymedphys/pymedphys/actions/runs/326673147

image

**Comment by sjswerdloff** [comment]
>with this extra tooling, are you in a position to take another look at the cypress test, and see if you can get it to pass locally using the above command?

Yes, I will be taking a crack at this.

**Comment by sjswerdloff** [comment]
The tests now pass in my development environment, but I had to add the file upload command:
see https://www.npmjs.com/package/cypress-file-upload

I also added:
https://www.npmjs.com/package/cypress-image-snapshot
but then commented out the use of that command (one can get it to work, but one has to 
Run Cypress with --env updateSnapshots=true in order to create/update the base image files for the tests).
I didn't try to remove it or references to it.
But even when it does work, it's sensitive to the size of the browser window (probably not an issue for CI/automated testing, but a hassle for local development/testing).

Once this passes in the CI environment, I still need to add testing of the outcome of the Pseudonymise button as well as downloading the resulting links.

**Comment by SimonBiggs** [comment]
> I also added:
> [npmjs.com/package/cypress-image-snapshot](https://www.npmjs.com/package/cypress-image-snapshot)
> ...
> But even when it does work, it's sensitive to the size of the browser window

Do we need to be checking for visual regressions? I'd argue we don't need to do any visual regression testing and don't need snapshot match testing at all.

When I mentioned e2e testing I was thinking more of validating that one can click the buttons and have the data be appropriate using the GUI. Not so much that every pixel stays exactly the same.

**Comment by sjswerdloff** [comment]
I started from the example found online.
I don't think visual presentation other than text is relevant.
So I'm very comfortable with not using image matching at all.

**Comment by SimonBiggs** [comment]
> So I'm very comfortable with not using image matching at all.

Awesome :)

**Comment by sjswerdloff** [comment]
@SimonBiggs , I'm having difficulty getting sidebar to appear and recognized for examination of
href related text (in cypress).  Any suggestions?  I have read that click() in cypress isn't quite the same as a user click...

**Comment by SimonBiggs** [comment]
> @SimonBiggs , I'm having difficulty getting sidebar to appear and recognized for examination of
> href related text (in cypress). Any suggestions? I have read that click() in cypress isn't quite the same as a user click...

Hopefully I can jump on this tonight :)

**Comment by SimonBiggs** [comment]
> Hopefully I can jump on this tonight :)

@sjswerdloff sorry I haven't got to this one yet.

**Comment by SimonBiggs** [comment]
@sjswerdloff let's merge this in, I'll extract out the extra testing needed into an issue.

**Pull request merged**
