### PR TITLE
[MRG] Str(e) to str(e.value)

### PR DESCRIPTION
**Pull request by Matthew-Jennings**

### CODE REVIEW

**Comment by SimonBiggs** [comment]
I feel a bit bad taking you away from your holiday...

**Comment by SimonBiggs** [comment]
I still don't get what caused this...

**Comment by SimonBiggs** [comment]
There we go, that's the difference:

pytest version 5.0.0:

Changelog:

https://docs.pytest.org/en/latest/changelog.html#removals

Relevant issue:

 https://github.com/pytest-dev/pytest/issues/5412

**Comment by SimonBiggs** [comment]
@pchlap has fixed this issue. It was due to an upgrade in pytest to 5.0.0. see the above comment. This can now be merged into your branch.

**Comment by Matthew-Jennings** [comment]
Yeah, I was thinking it had to be an update to a dependency. I was actually thinking Python itself, but hadn’t gotten around to checking the logs between passing and failing tests to interrogate package versions! Anyway, nice find :)

**Comment by SimonBiggs** [comment]
Oh? You didn't find that? How did you fix it without finding that?

**Comment by SimonBiggs** [comment]
Ahh, your prints :)

**Comment by Matthew-Jennings** [comment]
I re-checked the `pytest.raises()` example code and noticed it had changed from asserting x in `str(excinfo)` to asserting x in `str(excinfo.value)`.

I hadn’t made the leap to recognising `pytest` had updated, I’d actually thought it was Python itself. I’d mistakenly thought `excinfo` Referred to Python Exception info, but now I see that was silly, it’s actually part of `pytest`.

**Comment by SimonBiggs** [comment]
I'll let @pchlap do the merge given it's his branch

**Pull request merged**
