### PR TITLE
[WIP] Medical physics workshop

### PR DESCRIPTION
**Pull request by SimonBiggs**
@Centrus007 @sunyu0410

Here is my initial work for the workshop.

Once this branch is built the docs for it should appear at https://pymedphys.com/en/medical-physics-workshop/projects/workshops/2019-acpsem-ml/index.html

My thought process was to have the problems, and examples, all provided as Jupyter Notebooks.

As a sort of placeholder I have also imported some prereading material... We could link to those within the problem sets and examples so that people can go to reference material when needed...

### CODE REVIEW

**Comment by SimonBiggs** [comment]
Having trouble with something working locally but not online... Couldn't
get to the bottom of it :(

**Comment by Centrus007** [comment]
Not that I mind, but do we desperately need the reference material *in* pymedphys?

**Comment by SimonBiggs** [comment]
> Not that I mind, but do we desperately need the reference material in pymedphys?

Certainly don't. I was planning on editing it though, as in adding a pydicom section, as well as filtering it back to just what is needed...

**Comment by SimonBiggs** [comment]
Closed in favour of https://github.com/pymedphys/pymedphys/pull/169

No prereading included now.

**Pull request closed without merging**
