### PR TITLE
[WIP] The great prune

### PR DESCRIPTION
**Pull request by SimonBiggs**

### CODE REVIEW

**Comment by SimonBiggs** [comment]
Heya @pchlap,

To bring us closer to a `1.0.0` release I have migrated a lot of code to the labs. 
Given some of the issues with the pinnacle code I have migrated it as well as my mephysto and monaco code to the labs.

Sorry about that. Once I have finished this pull request I would be keen if you could have a look to make sure you're happy with the code being in the labs in the way I have put it in there.

Cheers :),
Simon

**Comment by SimonBiggs** [comment]
Given so much has changed in this PR the "Files changed" tab will mostly be meaningless. Instead, best to just look directly at the file tree in the branch itself:

https://github.com/pymedphys/pymedphys/tree/the-great-prune

**Comment by pchlap** [comment]
> Heya @pchlap,
> 
> To bring us closer to a `1.0.0` release I have migrated a lot of code to the labs.
> Given some of the issues with the pinnacle code I have migrated it as well as my mephysto and mosaiq code to the labs.
> 
> Sorry about that. Once I have finished this pull request I would be keen if you could have a look to make sure you're happy with the code being in the labs in the way I have put it in there.
> 
> Cheers :),
> Simon

Sounds good to me. Yeah just let me know when it's ready and Ill take a look :)

**Comment by SimonBiggs** [comment]
Note to self:

Next step, set up GitHub actions with new repo development install method

**Comment by SimonBiggs** [comment]
@Matthew-Jennings as a part of the prune I've been pulling the API back to the bare minimum to achieve functionality. One decision I made is that we only need to expose anonymised dataset as a part of the library API. If someone is using the library themselves that exposes the primary functionality:

https://github.com/pymedphys/pymedphys/blob/the-great-prune/src/pymedphys/dicom.py

I've also swapped to using `poetry` instead of `yarn`. And heaps of other stuff. Feel free to review if you are up to it. I wouldn't bother looking at the files changed, as too much as has changed. No stress if you're not in a position to review.

**Comment by SimonBiggs** [comment]
@pchlap @Matthew-Jennings I'm going to merge this one, more than happy to revert things if there are issues though. I tried to minimally impact other people's code, I did move a few locations, but the code structure hasn't been touched. 

I know I mostly like to find things where I left them when coding :).

I figure I'll merge this and then iterate on things such as https://github.com/pymedphys/pymedphys/issues/431 in smaller pull requests so that the files changed is actually informative.

In practice here there have been some sweeping changes to what is exposed via the top level pymedphys repo. I'm not exactly happy with where it is sitting right now, especially the dose and coord export. But mostly the internal things have been left untouched.

I have removed all sub packages and made them into modules of pymedphys, so it is all just one package.

I have removed yarn, all installation is now down with poetry and pip.

I have successfully removed the need for conda within the CI, meaning everything is pip installable!! (yayy). I have also implemented GitHub actions so that all CI testing is done on both Azure Pipelines and GitHub actions.

Next steps, refine the API a bit more until we have something we're quite happy beginning to stabalise, then double down on the docs addressing the following issue https://github.com/pymedphys/pymedphys/issues/416.

**Comment by SimonBiggs** [comment]
As a very next step though, I think I'll update the contributor docs page. (Will probably do that before calling it a night tonight).

**Comment by SimonBiggs** [comment]
Also, @pchlap if you're wondering why all your code is styled differently, sorry about that :(. That wasn't actually this pull request, it was one from a while ago where we forced black formatting across the whole repo.

It was one of those "rip the band-aid now" moments. And in the long run I think it'll be worth it. 

Sorry again.

**Pull request merged**
