### PR TITLE
Update active contributors list

### PR DESCRIPTION
**Pull request by nlambriICH**
Updating the contributors list as per #1638.

### CODE REVIEW

**Comment by SimonBiggs** [comment]
I jumped in to see if I can fix the propagate issue.

**Comment by nlambriICH** [comment]
I thought I had my fork up to date with main. Still don't know why there's a premission denied error now...

**Comment by SimonBiggs** [comment]
> I thought I had my fork up to date with main.

You did :slightly_smiling_face:, I made a change trying to fix your issue :slightly_smiling_face:

**Comment by SimonBiggs** [comment]
It seems I need to change the following to have write permissions to external forks:

https://github.com/Drassil/action-package-version-bump/blob/a4caade1bd6ec37db508f19812355a30506eee9c/.github/workflows/test.yml?rgh-link-date=2022-03-27T14%3A31%3A49Z#L8-L9

Would you be able to press Update branch and see how we go?

image

**Comment by SimonBiggs** [comment]
Hmm, the tests are passing... but they're doing the wrong thing it seems :slightly_frowning_face:.

All of this propagate nonsense is really just trying to automate the running and committing of the changes that result when you run `poetry run pymedphys dev propagate`.

For now, would you be able to run that locally and then commit the changes. We'll need to get to the bottom of why this propagate command doesn't like external forks :/

**Comment by nlambriICH** [comment]
Sure, I'm running it locally. I'll push the changes once it's finished

**Review by sjswerdloff — COMMENTED** [review]
setup.py has many changes and repetitive entries.
@SimonBiggs can you confirm whether these setup.py changes are intentional?

**Review by sjswerdloff — APPROVED** [review]

**Comment by SimonBiggs** [comment]
Woo hoo! Thanks Nicola :)

image

**Pull request merged**
