### PR TITLE
Delete prototyping, adjust team attribution

### PR DESCRIPTION
**Pull request by SimonBiggs**
Mike posted confusion around the notebooks found within the prototyping directory over at:

https://pymedphys.discourse.group/t/windows-setup/128/2?u=simonbiggs

For now, to reduce confusion, I have deleted this directory. The code will still be available though by looking back into the git history:

https://github.com/pymedphys/pymedphys/tree/e59e9dc25a0fb766a713b2bfcf82b10d2bc2105a/prototyping

While I was at it, I also updated the team details:

https://github.com/pymedphys/pymedphys/blob/remove-prototyping/README.rst

### CODE REVIEW

**Review by Matthew-Jennings — APPROVED** [review]
LGTM :)

**Comment by SimonBiggs** [comment]
Thanks @Matthew-Jennings :)

**Comment by sjswerdloff** [comment]
a bit late, but I did take a look earlier today (from my phone) and was going to more carefully review from a laptop.
I encourage you @SimonBiggs to put up your own logo (whether personal or corporate) when time permits

**Comment by SimonBiggs** [comment]
> I encourage you @SimonBiggs to put up your own logo (whether personal or corporate) when time permits

Yup :), I need to make a logo first :)

**Pull request merged**
