### PR TITLE
changed strategies from dict to immutables.Map

### PR DESCRIPTION
**Pull request by sjswerdloff**
made the dict private
created a private function to wrap the conversion to immutables.Map so that the additional key/value pairs used to store other control parameters/values can be addressed in the wrapping function.

### CODE REVIEW

**Comment by sjswerdloff** [comment]
@SimonBiggs this failed due to import magic.
I take it this means that a module level variable can not rely on a delayed import?

**Comment by sjswerdloff** [comment]
While I like the idea of using immutables, between having started with module level variables for the strategy rather than a function call, using immutables means having to make a breaking change to the API for the strategy itself, never mind the functions that use a strategy as a named/explicit/optional argument.

**Comment by sjswerdloff** [comment]
I'm not OK with this situation.
I'd rather close the PR and rethink it.

**Comment by SimonBiggs** [comment]
> I take it this means that a module level variable can not rely on a delayed import?

Yup, that's the key. The trick is, that file needs to be able to be imported, and everything at module level run, without having `immutables` installed.

**Pull request closed without merging**
