### PR TITLE
Document pseudonymisation api and tweak pyproject.toml to nudge streamlit pylint issue

### PR DESCRIPTION
**Pull request by sjswerdloff**
I'm not able to get the pseudonymisation_dispatch member to appear, so this isn't good to go.
But, it's a starting point for the documentation and it's a nudge on the streamlit pylint issue.

### CODE REVIEW

**Comment by sjswerdloff** [comment]
Interesting failures.
@SimonBiggs it doesn't seem that the change to pyproject.toml had an impact on _streamlit or streamlit.ScriptRunner related code.

**Comment by SimonBiggs** [comment]
Instead of bumping streamlit up, instead I am holding it back in the following:

https://github.com/pymedphys/pymedphys/pull/998

Which should hopefully fix all the issues. I can then choose to explicitly upgrade it instead.

**Comment by SimonBiggs** [comment]
So, streamlit was fixed by the above... but that weird cffi bug also crept in. Fixed that in the following:

https://github.com/pymedphys/pymedphys/pull/1000

**Comment by sjswerdloff** [comment]
discard in favor of alternative PRs

**Pull request closed without merging**
