### PR TITLE
Update urls.json

### PR DESCRIPTION
**Pull request by guanfada**

### CODE REVIEW

**Comment by SimonBiggs** [comment]
Hi @guanfada,

Are you able to update your fork to the latest version of PyMedPhys?

image 

You can achieve this by clicking Fetch Upstream > Fetch and Merge:

image

**Comment by guanfada** [comment]
Done.
image

**Comment by SimonBiggs** [comment]
@guanfada, could you do that again for me?

I'm trying to see if I can fix the error you're getting here :slightly_smiling_face:

**Comment by guanfada** [comment]
@SimonBiggs done again.

**Comment by SimonBiggs** [comment]
Awesome :slightly_smiling_face: 

Thanks for doing that. The one that was broken is now fixed :slightly_smiling_face: 

image

I'll leave my approval, and once all the tests pass you can press the "Merge pull request" button.

**Review by SimonBiggs — APPROVED** [review]

**Comment by SimonBiggs** [comment]
Also, @guanfada, given all the recent contributions you should make a PR that adds yourself to the PyMedPhys team! :balloon: :slightly_smiling_face: 

https://github.com/pymedphys/pymedphys#active-contributors

**Comment by guanfada** [comment]
@SimonBiggs Thanks so much! I don't know where I can make a PR. When I clicked on new pull request, it took me to a page of "compare changes"

**Comment by SimonBiggs** [comment]
> @SimonBiggs Thanks so much! I don't know where I can make a PR. When I clicked on new pull request, it took me to a page of "compare changes"

Probably best opening a new issue.

@pchlap when he makes that issue, might you be in a position to give him a hand adding himself to the team list?

**Comment by SimonBiggs** [comment]
Once you press the following button this merge will be complete:

image

:slightly_smiling_face:

**Pull request merged**
