### PR TITLE
adding a couple of utilities for manipulating oncentra structures

### PR DESCRIPTION
**Pull request by peterg1t**
This update add a couple of utilities for manipulation of structures. DICOM files of structures drawn in mpMRI exported from MIM can be rotated due to the registration. oncentra_struct_rot.py allow to rotate these structures slices so they are parallel to the XY plane and therefore imported in oncentra correctly. oncentra_struct_shift allow to shift any structure around. This is useful when structures are outside of the TRUS range.

### CODE REVIEW

**Comment by SimonBiggs** [comment]
Hi @peterg1t,

Hope everything is going okay for you in Canada. Were you keen on getting these tests passing for a merge? Or would you like me to close this pull request?

**Comment by peterg1t** [comment]
Hi Simon,
So sorry for the late reply with the COVID outbreak things have gotten super crazy. Thankfully we are just doing fine. I hope you are doing ok as well. I'm definitely keen on working on fixing these issues. 
Best regards,

Pedro

**Comment by SimonBiggs** [comment]
No need to be sorry, the current climate is certainly mental. We are also doing relatively well.

Certainly some rough moments, but our ship is relatively smooth sailing compared to some of the wild oceans out there at the moment.

**Comment by SimonBiggs** [comment]
Change of heart?

**Comment by peterg1t** [comment]
Hi Simon,
Thanks for your help with this. I tough it would be easier to create a new pull request. Is this ok?
Thanks again!

**Comment by SimonBiggs** [comment]
Yeah of course :) feel free to experiment like that to find something that works.

**Pull request closed without merging**
