### PR TITLE
Fixes #973 issue with pinnacle export CLI

### LINKED ISSUE #973: @pchlap Pinnacle experimental tools line command
Hi Phillip,
Thank you for the Pinnacle tar to DICOM tool. It is very nice.

However, being a python and pymedphys novice, I have a few problems when I try running it in command line.
I was able to use the -m option and export only dose, plans and structures, but I have not been able to pause the script, read the available plans, select the one I need and export a specific trial within it.

Is there a way I can do this?

Thanks in advance

Sotiri

### PR DESCRIPTION
**Pull request by pchlap**
This fixes the issue reported in #973 where the trial couldn't be set using the command line interface.

@SimonBiggs I don't have a test which covers this code, since it's part of the CLI. Would you expect to have a test for the CLI functions?

### CODE REVIEW

**Comment by SimonBiggs** [comment]
> Would you expect to have a test for the CLI functions?

Yup, certainly, if that's okay.

Here is an example:

https://github.com/pymedphys/pymedphys/blob/ed39ad7850c57227cf9f2b15e31b18cfcf170660/pymedphys/tests/dicom/test_header_tweaks.py#L44-L54

Although there I removed the file after, it is much better to use a temp directory like the following:

https://github.com/pymedphys/pymedphys/blob/ed39ad7850c57227cf9f2b15e31b18cfcf170660/pymedphys/tests/experimental/pseudonymisation/test_pseudonymisation.py#L92-L114

**Comment by SimonBiggs** [comment]
You can feel free to ignore the following test failure:

image

Unfortunately it is intermittent... I need to get to the bottom of that :(.

**Comment by pchlap** [comment]
> > Would you expect to have a test for the CLI functions?
> 
> Yup, certainly, if that's okay.

Cool, thanks for the examples. I'll sort that out, hopefully I can get that done tomorrow morning :)

**Comment by pchlap** [comment]
Hi @SimonBiggs ,

I've added some tests for the CLI, let me know what you think. If you're happy we can merge this and let it roll out in the next release. Thanks a lot!

**Pull request merged**
