### PR TITLE
CC Solution Single patient multiple trials (Pinnacle Export cli)

### PR DESCRIPTION
**Pull request by crcrewso**
Resolves issue #1635 

Warning - this implementation isn't the most human readable, created only for expediency. 

Future solution would reverse the assumptions of the code. 
- Currently code assumes one plan per patient 
- Future implementation should assume that all plans per patient be exported
  - This should be accomplishable without changing inputs

This implementation wraps a while loop around the export actions to execute for each plan found, if no specific plan or trial is specified.

### CODE REVIEW

**Comment by SimonBiggs** [comment]
Will need a test to cover the new code so as to support maintainability into the future. A good set of rules for accepting a PR can be found within the following standard of code review document:

https://google.github.io/eng-practices/review/reviewer/standard.html

Where the overarching rule is:

> In general, reviewers should favor approving a [PR] once it is in a state where it definitely improves the overall code health of the system being worked on, even if the [PR] isn’t perfect.

**Comment by SimonBiggs** [comment]
@crcrewso, also, do you have interest being included on the "our team" page? There's also the potential of being included on the paper if you were interested? Once this PR is merged in, let's get you into both of those if you're keen.

**Comment by SimonBiggs** [comment]
Hi @crcrewso,

Just wanting to check if you're happy to add a test to cover this feature and include it within this PR?

Cheers,
Simon

**Comment by crcrewso** [comment]
Absolutely I am, I'd like to take some time to clean up the code at the same time. Should be done next week. Would it be cleaner to close the merge request and reopen when ready?

**Comment by SimonBiggs** [comment]
> Would it be cleaner to close the merge request and reopen when ready?

All good :slightly_smiling_face:, keep it open :slightly_smiling_face:.

**Comment by SimonBiggs** [comment]
> Should be done next week. Would it be cleaner to close the merge request and reopen when ready?

Hi @crcrewso, if this one will still be a while then it might be better to do a close and then create a new PR when you're ready...

**Comment by crcrewso** [comment]
> > Should be done next week. Would it be cleaner to close the merge request and reopen when ready?
> 
> Hi @crcrewso, if this one will still be a while then it might be better to do a close and then create a new PR when you're ready...

That's probably the best idea

**Pull request closed without merging**
