### PR TITLE
Remove special MacOS install instructions

### PR DESCRIPTION
**Pull request by SimonBiggs**
`pymssql` has a new maintainer. They've produced MacOS wheels! :) Yay. So No longer will I need special macos install instructions.

### CODE REVIEW

**Review by sjswerdloff — APPROVED** [review]

**Comment by sjswerdloff** [comment]
has the version for pymssql been set so the wheel will be available?

**Comment by SimonBiggs** [comment]
> has the version for pymssql been set so the wheel will be available?

Given our software can work with previous versions it is not a library's responsibility (in fact they certainly shouldn't) lock out versions that it is possible to work with. Package managers will at times refuse to install software if a non-conflicting version pinning cannot be found. If we were using a feature of pymssql that required the latest version, then we'd pin it. If we were utilising private APIs or unstable APIs that provide no stability guarantee, then we should also pin it. Otherwise not.

**Comment by SimonBiggs** [comment]
> > has the version for pymssql been set so the wheel will be available?
> 
> Given our software can work with previous versions it is not a library's responsibility (in fact they certainly shouldn't) lock out versions that it is possible to work with. Package managers will at times refuse to install software if a non-conflicting version pinning cannot be found. If we were using a feature of pymssql that required the latest version, then we'd pin it. If we were utilising private APIs or unstable APIs that provide no stability guarantee, then we should also pin it. Otherwise not.

In the `requirements.txt` file however, and in the `poetry.lock` files we have pinned it:

https://github.com/pymedphys/pymedphys/blob/a42ac76680226f9e432af7c81d76658a376930ce/requirements.txt#L91

Just not the pyproject.toml (or equivalently the setup.py)

**Comment by sjswerdloff** [comment]
> > > has the version for pymssql been set so the wheel will be available?
> > 
> > 
> > Given our software can work with previous versions it is not a library's responsibility (in fact they certainly shouldn't) lock out versions that it is possible to work with. Package managers will at times refuse to install software if a non-conflicting version pinning cannot be found. If we were using a feature of pymssql that required the latest version, then we'd pin it. If we were utilising private APIs or unstable APIs that provide no stability guarantee, then we should also pin it. Otherwise not.
> 
> In the `requirements.txt` file however, and in the `poetry.lock` files we have pinned it:
> 
> https://github.com/pymedphys/pymedphys/blob/a42ac76680226f9e432af7c81d76658a376930ce/requirements.txt#L91
> 
> Just not the pyproject.toml (or equivalently the setup.py)

If we delete instructions for how to install the earlier versions, then we are not really sypporting those ("possible to work with, but you'll have to figure out how to get it installed, and it used to be an N step process, so... best of luck").  But if it's in the poetry.lock and requirements.txt, then that's really what a user who "just wants to install it and get on with things" will get, and that's fine.

**Comment by SimonBiggs** [comment]
If someone runs `pip install pymedphys[user]` and they already have pymssql on their machine, they will keep their old version. But that means they have successfully installed it in the past. If they install it today without pymssql on their machine then it will get the latest version unless another one of our dependencies explicitly pins to not use the latest version.

**Comment by SimonBiggs** [comment]
If it helps, for an authoritative instruction on the topic, see:

> It is not considered best practice to use `install_requires` to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

-- https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires-vs-requirements-files

> Whereas `install_requires` requirements are minimal, requirements files often contain an exhaustive listing of pinned versions for the purpose of achieving repeatable installations of a complete environment.

-- https://packaging.python.org/discussions/install-requires-vs-requirements/#requirements-files

**Pull request merged**
