### PR TITLE
[MRG] expose trf2pandas, add a few experimental notebook examples

### PR DESCRIPTION
**Pull request by SimonBiggs**

### CODE REVIEW

**Comment by Matthew-Jennings** [comment]
`trf2pandas()` is neither documented nor tested. I do think we should start to be strict with this for the `master` branch of PyMedPhys proper. Postponing until some other time prior to next release is a sure-fire recipe for it never getting done!

Perhaps interested users can be given early, undocumented, untested access to functions like this in separate branches?

**Comment by SimonBiggs** [comment]
`trf2pandas` certainly is tested. See https://github.com/pymedphys/pymedphys/blob/master/packages/pymedphys_fileformats/tests/trf/test_decode.py

**Comment by Matthew-Jennings** [comment]
I see `trf2csv`, but no `trf2pandas`...

**Comment by SimonBiggs** [comment]
trf2csv is just trf2pandas with pandas in built (tested) to_csv method.

**Comment by SimonBiggs** [comment]
https://github.com/pymedphys/pymedphys/blob/master/packages/pymedphys_fileformats/src/pymedphys_fileformats/trf/trf2csv.py#L65-L68

**Comment by Matthew-Jennings** [comment]
Ah yes, I see. My mistake.

But the documentation point still remains.

**Comment by SimonBiggs** [comment]
> Ah yes, I see. My mistake.
> 
> But the documentation point still remains.

I agree with the docs. I had a read of the following https://www.divio.com/blog/documentation/

I noted it here https://github.com/pymedphys/pymedphys/issues/416

I am actually considering a complete re-work of the docs based on it. And I want to do that in unison with our next major API adjustment.

I have been talking to @msobolewski, I think I might be able to get some time in the nearish future to undergo this documentation re-write and fill out.

Once that is complete, I will expect that every exposed API will have a Reference, How-To, and Explanation (as defined in that linked article).

Until that time, lets not block things due to documentation. But the day when we block based on docs will come, and it will come before a 1.0.0 release.

**Comment by Matthew-Jennings** [comment]
Okay :)

**Pull request merged**
