### PR TITLE
Qcheck tests

### PR DESCRIPTION
**Pull request by ayalalazaro**
Hi Simon,

I have written some tests for the quickcheck code. I mocked a Quickcheck device and tested the class methods.
I have used unittest because it is the test suite I am more comfortable with, I hope it complies with the project.

please let me know any issues you find. :)

### CODE REVIEW

**Comment by SimonBiggs** [comment]
@pchlap or @sjswerdloff would either of you be in a position to help @ayalalazaro out?

**Comment by sjswerdloff** [comment]
Is there a description of what QuickCheck is, what it's supposed to accomplish?
Some docstring for the Class and for the functions in the class would be helpful.
In looking at the CI (tests), there are failures in a variety of places where it seems like one would want it to pass (things like Ubuntu/update I am not too worried about.  Precommit... I worry about.)
In the test, it looks like one needs to know an awful lot about what the content is supposed to look like.

**Comment by crcrewso** [comment]
I think this is the [quickcheck](https://www.ptwdosimetry.com/en/products/quickcheck-webline/) @ayalalazaro is refering to.

**Comment by ayalalazaro** [comment]
I am sorry, @sjswerdloff you are right I should have written some documentation of the class and its methods. As @crcrewso stated, Quickcheck is a linac daily QA device from PTW. The code connects to the device (connected with ethernet cable and given an accesible IP) and allows the user to retreive the measurements as a pandas dataframe which can be saved as csv too. At my institution we use it in a daily cron job to push data to QATrack+.
I will try to fix pre-commit failures but I am not sure what you mean with 

> In the test, it looks like one needs to know an awful lot about what the content is supposed to look like.

do you mean that I have to add comments to the test?

**Comment by crcrewso** [comment]
@ayalalazaro 
Is this the ideal project for this or would it make more sense to incorporate it into [pylinac](https://pylinac.readthedocs.io/en/release-3.0/) ([pylinac github](https://github.com/jrkerns/pylinac) )

**Comment by crcrewso** [comment]
> @crcrewso I don t think it is suitable for pylinac. Pylinac is a set of automated linac QA procedures it does not manage connections with equipment. In this repository there are scripts that connect or interact with different kinds of devices: Mosaiq, Sun Nuclear Profiler, Pinnacle, Mephysto files among others.

I'm not trying to be argumentative here but, I was not aware of any direct connections to anything other then Mosaiq in this code base. I thought the SNC, Pinnacle, and PTW relationships were all file format parsing. 

@randlet has written a tool to replace those cron jobs [QATrack's companion QC injector](https://github.com/qatrackplus/qcpump) thinking about this more maybe that would be a good fit

Either way I do have some direct comments/questions
- To avoid dns collisions should your test IP be 127.0.0.1 (localhost)
- Does your code support hostnames? 
- A google search of QuickCheck leads me to think maybe refactoring to PTWQuickCheck would be nicer 

If my site ever switches from the SNC DQA3 to PTW QuickCheck I will be extremely thankful

**Comment by ayalalazaro** [comment]
> I'm not trying to be argumentative here but, I was not aware of any direct connections to anything other then Mosaiq in this code base. I thought the SNC, Pinnacle, and PTW relationships were all file format parsing.

There is Mosaiq and Integrity ICOM connection, but I think you are right about the others.


> Either way I do have some direct comments/questions
> 
>     * To avoid dns collisions should your test IP be 127.0.0.1 (localhost)
Sure, 127.0.0.1 is alright too. I didn t think of that since it is monkeypatched. Anyway, I prefer localhost too
>     * Does your code support hostnames?
Yes, it does, I guess it should be documented somewhere
>     * A google search of QuickCheck leads me to think maybe refactoring to PTWQuickCheck would be nicer

PTWQuickCheck is ok for me, I just wonder if there are any legal issues for using trademarks directly. 
 
> If my site ever switches from the SNC DQA3 to PTW QuickCheck I will be extremely thankful

Thank you

There are some checks that fail in the pull_request (ubuntu, propagate), I have no idea how to fix this error:

 `Building pymedphys (0.38.0)
   - Building sdist
   - Built pymedphys-0.38.0.tar.gz
 fatal: couldn't find remote ref qcheck_tests
 Error: Process completed with exit code 128.`

> @randlet has written a tool to replace those cron jobs [QATrack's companion QC injector](https://github.com/qatrackplus/qcpump) thinking about this more maybe that would be a good fit

You may be right, but at this moment I don t know what to do. The code was in pymedphys long ago, in labs module, way before QCPump project. Right know, I just created some tests and fixed some issues with the original code. I think it is not a good idea to contribute to another repository with the same code, it does not seem right for me.

**Comment by crcrewso** [comment]
> Right know, I just created some tests and fixed some issues with the original code. I think it is not a good idea to contribute to another repository with the same code, it does not seem right for me.

My apologies, I thought this was adding this feature to the code, not improving existing features. Since it's in, you're right, maintainability first!

**Comment by ayalalazaro** [comment]
@crcrewso 
I have changed the ips to 127.0.0.1 and added some more docstrings. The docstring of the QuickCheck class states that a hostname can be used.

**Review by sjswerdloff — APPROVED** [review]

**Comment by sjswerdloff** [comment]
@SimonBiggs it's not clear if

> fatal: couldn't find remote ref qcheck_tests

in the propagate test is a "real" issue.  But everything else LGTM

**Comment by sjswerdloff** [comment]
@ayalalazaro thank you for adding docstring to the original code.
This allowed me, and will likely allow others to quickly grasp what they can do with the code and how to make use of it for their specific needs.

**Comment by ayalalazaro** [comment]
> @ayalalazaro thank you for adding docstring to the original code. This allowed me, and will likely allow others to quickly grasp what they can do with the code and how to make use of it for their specific needs.

Thanks for making the code clearer!

**Comment by SimonBiggs** [comment]
> @crcrewso I have changed the ips to 127.0.0.1 and added some more docstrings. The docstring of the QuickCheck class states that a hostname can be used. I am still don t unsderstand the error in ubuntu (propagate).

I can chime in here. That propagate error came from it not being able to access this branch. All good. Thank you for this work :) I've merged them in :)

**Pull request merged**
