### PR TITLE
0.39.0 release prep

### PR DESCRIPTION
**Pull request by pchlap**

### CODE REVIEW

**Comment by pchlap** [comment]
Hi @SimonBiggs, @Matthew-Jennings & @sjswerdloff,

in preparation for this release, I am checking the PRs which have been merged since the last release. You can see two items in the changelog now (one was preemptively added by @Matthew-Jennings which was nice). Most of the PRs had to do with adjusting documentation, repo maintenance, and of course the JOSS paper prep. I wonder if any of these are worth noting in the changelogs?

There have also been some contributors added. However, I don't think we have highlighted these in the past.

Finally, I just want to check if there is anything else I've missed from your perspective? Thanks.

**Comment by Matthew-Jennings** [comment]
I have no strong preference, but, of the items you mentioned, perhaps we should include a statement on the JOSS paper. It probably makes sense to note within the CHANGELOG which version was reviewed for this JOSS paper. Note also that it's possible that [additional JOSS articles on PyMedPhys](https://joss.readthedocs.io/en/latest/submitting.html#should-i-write-my-own-software-or-contribute-to-an-existing-package) are published in the future.

I can add a line or two to that effect.

**Comment by pchlap** [comment]
> I have no strong preference, but, of the items you mentioned, perhaps we should include a statement on the JOSS paper. It probably makes sense to note within the CHANGELOG which version was reviewed for this JOSS paper. Note also that it's possible that [additional JOSS articles on PyMedPhys](https://joss.readthedocs.io/en/latest/submitting.html#should-i-write-my-own-software-or-contribute-to-an-existing-package) are published in the future.
> 
> I can add a line or two to that effect.

Sounds good, thanks @Matthew-Jennings!

**Comment by Matthew-Jennings** [comment]
I might just wait for a response to https://github.com/openjournals/joss-reviews/issues/4555#issuecomment-1261682948 prior to editing the CHANGELOG.

**Comment by Matthew-Jennings** [comment]
Perhaps we can issue a release as is and then edit the CHANGELOG with the JOSS details afterwards? I don't think this CHANGELOG entry needs to hold up a release.

**Comment by SimonBiggs** [comment]
The dev install extras scope has been reduced, and a new install extras called all has been made:

https://github.com/pymedphys/pymedphys/pull/1710/files

**Comment by SimonBiggs** [comment]
> I might just wait for a response to [openjournals/joss-reviews#4555 (comment)](https://github.com/openjournals/joss-reviews/issues/4555#issuecomment-1261682948) prior to editing the CHANGELOG.

No need to wait here. Adding in this note into the changelog for 0.39.0 is appropriate.

**Comment by Matthew-Jennings** [comment]
> > I might just wait for a response to [openjournals/joss-reviews#4555 (comment)](https://github.com/openjournals/joss-reviews/issues/4555#issuecomment-1261682948) prior to editing the CHANGELOG.
> 
> No need to wait here. Adding in this note into the changelog for 0.39.0 is appropriate.

Might not the CHANGELOG note belong under 0.38.0, depending on @osorensen's answer?

**Comment by Matthew-Jennings** [comment]
> > > I might just wait for a response to [openjournals/joss-reviews#4555 (comment)](https://github.com/openjournals/joss-reviews/issues/4555#issuecomment-1261682948) prior to editing the CHANGELOG.
> > 
> > 
> > No need to wait here. Adding in this note into the changelog for 0.39.0 is appropriate.
> 
> Might not the CHANGELOG note belong under 0.38.0, depending on @osorensen's answer? His original comments, at least according to my interpretation, imply that 0.38.0 is the reviewed version. [It even says as much in the original review issue](https://github.com/openjournals/joss-reviews/issues/4555#issue-1297894218)

I'll just put it in anyway. We can move it if necessary

**Comment by pchlap** [comment]
> I'll just put it in anyway. We can move it if necessary

Thanks @Matthew-Jennings, I moved it to `News around this release` section, hope thats ok.

**Comment by pchlap** [comment]
@SimonBiggs,

I think this is just about ready to go. I am just a little hazy on the final steps of the release. I am preparing a document to use as a guide in the future. Would you happen to have 15 mins spare (either today at 5pm, or tomorrow morning at around 8am) to go through the final steps? Alternatively I can share my doc with you and you can correct/supplement the bits I'm unsure of in bullet point format?

**Review by SimonBiggs — APPROVED** [review]
LGTM :)

**Comment by SimonBiggs** [comment]
> I am just a little hazy on the final steps of the release.

Next steps are to follow the following two steps to publish the release:

* https://python-poetry.org/docs/libraries/#packaging
* https://python-poetry.org/docs/libraries/#publishing-to-pypi

Then create and tag a release:
https://github.com/pymedphys/pymedphys/releases

And copy in the changelog into the release description.

**Comment by pchlap** [comment]
> > I am just a little hazy on the final steps of the release.
> 
> Next steps are to follow the following two steps to publish the PyPI release:
> 
> * https://python-poetry.org/docs/libraries/#packaging
> * https://python-poetry.org/docs/libraries/#publishing-to-pypi
> 
> Then create and tag a GitHub release: https://github.com/pymedphys/pymedphys/releases
> 
> And copy in the changelog into the release description.
> 
> Then lastly, do a manual sanity check and install from PyPI and run the tests from within the PyPI downloaded package.
> 
> > Would you happen to have 15 mins spare (either today at 5pm, or tomorrow morning at around 8am) to go through the final steps?
> 
> Let's see if I can keep helping via GitHub comments, that way we have a text record, which, if you so desire, you can copy into the document you're building up.

Thanks @SimonBiggs! That sounds fairly straightforward so I think we'll be fine doing this via GitHub comments. I'll let you know how it goes :)

**Pull request merged**
