### PR TITLE
preparing for a dev release 0.35.0-dev2

### PR DESCRIPTION
**Pull request by sjswerdloff**
I assume I should get this merged and then publish?
merge, fetch and publish? (which means the repo should not have any additional merges to main between the merge and fetch)?

Please Cancel the PR if this isn't necessary/appropriate (and then I'll go find the maintainers documentation and start updating it...)

### CODE REVIEW

**Comment by sjswerdloff** [comment]
@SimonBiggs so... why does the (ubuntu, tests) fail on "See if propagate needed"?
```
poetry run pymedphys dev propagate
...
no changes added to commit (use "git add" and/or "git commit -a")
Error: Process completed with exit code 1.

```

I'm thinking a walk through might be helpful (during which I take notes and we create the first draft of the maintainers document).  However, it's also Friday night, so... maybe Monday?

**Comment by SimonBiggs** [comment]
Hi Stuart :),

Feel free to not respond to this tonight/tomorrow.

My main thought of what could be going on here is maybe your version of
poetry may need updating so that the requirements files being created match
with that created by the CI during its "did propagate occur" tests. Are you
running poetry version 1.1.4?

Regarding the merging before releasing, for a dev release I am okay if you
release straight from this branch before the merge if you'd like. Dev
releases are allowed to have non-main content.

**Comment by sjswerdloff** [comment]
I did a 
poetry self update

But I think that happened after I did the propagate.  I didn't think to update poetry until the deploy command failed.

I'll repeat the propagate as soon as I get back to my desk (Sunday or Monday)

I noticed a change in how versions of packages were excluded...  But didn't understand the implications.

**Review by SimonBiggs — APPROVED** [review]
LGTM :)

**Pull request merged**
