### PR TITLE
[RFR] Focus on the phrases which will appear in searches

### PR DESCRIPTION
**Pull request by SimonBiggs**
Heya Matt,

These key phrases are the ones that appear in searches for PyMedPhys in Google. We need to be economical with words and get the message home. I'm keen for you to rework these bits yourself a bit also if you have ideas to word it better.

### CODE REVIEW

**Comment by Centrus007** [comment]
I had a go at re-wordng this and quickly realised that, if completely left to my own devices, it would look **VERY** different...

I think we need to revisit our "intention of PyMedPhys" discussion. The README as it stands is very geared toward encouraging _development_ (rather than _use_) and, more specifically, encouraging non-experts to contribute (e.g. "feel free to submit MatLab scripts"). I really don't think we should lean too far in that direction.

Veering to strongly toward the education side of things will ultimately detract from the quality of PyMedPhys and the contributor experience. Time is limited, so you really need to ask yourself: would you rather be spending your time writing quality tools with a team of quality collaborators, or do you want to assume the educator mantle and find yourself giving repeated, tedious instructions to non-experts just to get them started (only to find that they end up contributing little of value or abandon the project eventually).

**Comment by Centrus007** [comment]
My preference would be:
- Spend the time on quality code and docs to maximise **ease of use**.
- As a second priority, spend time maximising **ease of contribution** _for those with some baseline skill level_. Contributors should only need nudges, not tutorials. Quick answers to queries, not hours of "babying" through the process.

**Comment by SimonBiggs** [comment]
I think on this point we just need to agree that we have compatible but
differing priorities for PyMedPhys. I want a friendly, open, community that
helps turn an enthusiastic beginner programmer into someone who is a joy to
program with. The tools themselves will then are thought of as a great
byproduct of that.

I want the Python adage "people come to Python for the language, but stay
for the community" to be true of PyMedPhys also, and have that be
prioritised above almost anything else. And part of that being true is
being welcoming to all who wish to give it a go, whether they're going to
stick around or not. And, as a benefit, those who "stay for the community"
for years, will as a byproduct become proficient programmers, and in the
end that will raise the quality of PyMedPhys, not detract from it.

**Comment by Centrus007** [comment]
> I think on this point we just need to agree that we have compatible but differing priorities for PyMedPhys. I want a friendly, open, community that helps turn an enthusiastic beginner programmer into someone who is a joy to program with. The tools themselves will then are thought of as a great byproduct of that.

I want the Python adage "people come to Python for the language, but stay
for the community" to be true of PyMedPhys also, and have that be
prioritised above almost anything else. And part of that being true is
being welcoming to all who wish to give it a go, whether they're going to
stick around or not. And, as a benefit, those who "stay for the community"
for years, will as a byproduct become proficient programmers, and in the
end that will raise the quality of PyMedPhys, not detract from it.

**Comment by Centrus007** [comment]
Let's pull this in for now. I'll address your latest comment another time :)

**Comment by SimonBiggs** [comment]
Thanks Matt :) we'll work this stuff out :)

**Pull request merged**
