### PR TITLE
adding function to calculate sessions and session offsets

### PR DESCRIPTION
**Pull request by dg1an3**
also a notebook demonstrating the function
added a notebook using pandas.to_sql to create a mock db

### CODE REVIEW

**Comment by SimonBiggs** [comment]
Hi @dg1an3,

Thanks for this :slightly_smiling_face:. Just a quick heads up, the pre-commit failure is a sign that you need to undergo the following step on your local machine:

```
poetry run pre-commit install
```

From --https://docs.pymedphys.com/howto/advanced/setup-win.html#overview

One of the things pre-commit does is it removes all of the notebook output. This since notebook output often doesn't play nice with version control and it can sometimes contain sensitive information.

**Comment by SimonBiggs** [comment]
Also, after reading through your usage here, I can think of a few improvements to PyMedPhys:

* Make it so that the mosaiq connect method can accept an optional parameter "database name" so that custom database names can be pointed to
* Expose a "non-context-manager" version of mosaiq.connect. Given "with" statements lock you into one cell in a notebook it needs to be re-written each cell. Also, Mosaiq doesn't like having its connection opened and closed in quick succession, it can cause you to be booted off for a period of time.
* Have the "create a mock database" be a method within PyMedPhys itself
* Have these notebooks find their way over to the "howto" section of the docs (https://github.com/pymedphys/pymedphys/tree/main/lib/pymedphys/docs/howto) similar to https://docs.pymedphys.com/howto/gamma/effect-of-noise.html

**Comment by SimonBiggs** [comment]
Another thing pre-commit does is force all Python files to be in a consistent formatting using the tool black:

https://github.com/pymedphys/pymedphys/pull/1324/checks?check_run_id=1718506092#step:7:62

If you want to do this step yourself without installing pre-commit or poetry you can run:

```
pip install black==20.8b1
black ./prototyping/mosaiq/mosaiq-sessions-protocols/session_offsets_calculator.py
```

Cheers :)

**Review by SimonBiggs — APPROVED** [review]
LGTM 👍 🙂 

@dg1an3 let me know when you're happy for a merge and I'll merge it in 🙂

**Comment by dg1an3** [comment]
@SimonBiggs I'm not sure why the ubuntu updates test is failing -- any ideas?

**Comment by SimonBiggs** [comment]
> @SimonBiggs I'm not sure why the ubuntu updates test is failing -- any ideas?

All good, that was fixed in another PR. See comment at the end of https://github.com/pymedphys/pymedphys/pull/1324#issuecomment-761879501

**Comment by dg1an3** [comment]
Everything looks OK to me, so I guess we are good to merge

**Comment by SimonBiggs** [comment]
And she's in! :tada: :slightly_smiling_face:

**Comment by SimonBiggs** [comment]
If you're interested, consider adding yourself to the active contributors list:

https://github.com/pymedphys/pymedphys/blob/c8bb4db0f1562d283bbf937fbeea371816764e96/lib/pymedphys/docs/README.rst#L165-L195

**Pull request merged**
