### PR TITLE
[RFR] Previous theme customisation now inbuilt into our theme

### PR DESCRIPTION
**Pull request by SimonBiggs**

### CODE REVIEW

**Comment by SimonBiggs** [comment]
This was based off of the previous branch, hence the repeat commits. This is ready for merge, but essentially all this is, is merging our previous theme customisation into the theme itself.

**Comment by SimonBiggs** [comment]
Awesome :) good to merge :)

**Comment by SimonBiggs** [comment]
Thanks Matt :)

**Comment by SimonBiggs** [comment]
Also, font is changed back to what it was I think now?

**Comment by Centrus007** [comment]
Yep, I think so.

**Pull request merged**
