### PR TITLE
avoid crashing when --pseudo is not provided via experimental

### PR DESCRIPTION
**Pull request by sjswerdloff**
fallback to using release anonymisation strategy and keywords

### CODE REVIEW

**Comment by SimonBiggs** [comment]
LGTM, only addition would be to add a test that replicates the user's issue and has it fixed.

**Comment by sjswerdloff** [comment]
> LGTM, only IMO addition would be to add a test that replicates the user's issue and has it fixed.

That's what I'm working on...   I had to go remember how to run tests, and I wanted to make sure I hadn't run afoul of anything else...

FYI, when I run tests locally, I'm seeing a lot of warnings  involving size of strings exceeding accepted values for some elements of particular VR (SH and PN) that are being issued by pydicom 2.x 
I don't have time to dig in to that this weekend, but I'll take a closer look when I can find the time (probably not next weekend, maybe the following).

**Comment by sjswerdloff** [comment]
FYI, the failure in updates seems to be a timeout while running lint 
When I ran 
poetry run pymedphys dev lint
it hung, and then died when it finally caught a <Ctrl-Z> I tried to send it (hung my virtual machine).
This is where it hung/died:
Command '['/home/parallels/.pyenv/versions/3.9.14/envs/pymedphys39/bin/python', '-m', 'pylint', 'pymedphys', '--rcfile=/home/parallels/dev/pythonprojects/pymedphys39/pymedphys/lib/pymedphys/.pylintrc']'

**Comment by sjswerdloff** [comment]
confirmed in local testing that the output of experimental anonymise vs. anonymise was identical.

**Comment by SimonBiggs** [comment]
Beautiful, thanks Stuart.

> FYI, the failure in updates seems to be a timeout while running lint

Potentially the best path forward for this for now is to pin pylint to the most recently known working version. Given pylint isn't a user dependency the pin is not so bad, and it would be okay for it to hang around until we got to the bottom of the hang (or a more recent pylint version fixes it for us...)

**Review by SimonBiggs — APPROVED** [review]
LGTM :)

**Pull request merged**
