### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by fishdda**
add more items for linac_state_codes especially #34#

### CODE REVIEW

**Comment by fishdda** [comment]
> Awesome :) Thanks @fishdda for your first pymedphys contribution!

No probelm :-)

**Comment by SimonBiggs** [comment]
Ahh, that's unfortunate. It's broken something down the line (I used the state code column to try and detect whether it is Integrity4, 3 or Unity). I'll need to take this and work on it before we can merge.

**Comment by fishdda** [comment]
> Ahh, that's unfortunate. It's broken something down the line (I used the state code column to try and detect whether it is Integrity4, 3 or Unity). I'll need to take this and work on it before we can merge.

Yes, we only have integrity 4.0.3 and all tests were done on this version.

**Comment by SimonBiggs** [comment]
@fishdda can you provide me some of the trf files that you were hoping to be able to decode? Might you be able to attach them to this conversation?

**Review by SimonBiggs — CHANGES_REQUESTED** [review]
Before continuing with this change, need to be able to have copies of the TRF files that were not able to be decoded, and need these extra state codes added.

**Comment by SimonBiggs** [comment]
Hi @fishdda,

For now I'm going to close this PR. If you're able to provide the data that this PR is being implemented to address we can reopen it.

**Pull request closed without merging**
