### PR TITLE
Logos for linkedin

### PR DESCRIPTION
**Pull request by SimonBiggs**
In the specific resolution of the respective banners and avatars

### CODE REVIEW

**Comment by sjswerdloff** [comment]
These can't be viewed online particularly well.
The SVG don't look right within GitHub, they don't look too bad when downloaded, but they don't look like the PNG (the PNG look fine).
It might be easier to do a visual review by attaching the files to a comment (or perhaps taking a screenshot of the icons when viewed in the environment you expect them to be viewed, and generate a PDF from the screenshot... PDF tends to be pretty consistent in presentation no matter what platform)

**Review by sjswerdloff — APPROVED** [review]
see comment in conversation

**Comment by SimonBiggs** [comment]
SVGs likely just need the appropriate fonts installed:

```bash
sudo apt-get install fonts-roboto-slab
```

Also, re the visual review it might be best to see them in the wild, given that they were designed for Linkedin's resolutions:

image
image
https://www.linkedin.com/in/biggssimon/

image
https://www.linkedin.com/company/pymedphys/

**Comment by sjswerdloff** [comment]
well, the images are kind of clipped at the top.
But I'm not known as being focused on aesthetics.

**Comment by SimonBiggs** [comment]
> well, the images are kind of clipped at the top.

Yeah, I chose to have them clipped, the alternative was to make the logo quite a bit smaller.

**Pull request merged**
