### PR TITLE
[RFR] Graphs in docs

### PR DESCRIPTION
**Pull request by SimonBiggs**

### CODE REVIEW

**Comment by SimonBiggs** [comment]
@Centrus007 this is awesome! :)

https://5cda9a8ea5b3b1000854e028--pymedphys.netlify.com/developer/dependencies.html#package-dependencies

**Comment by SimonBiggs** [comment]
Once we merge this one in, let's cut the release then I'll write a post on the /r/Python Reddit describing how we've set up a Python Monorepo with lerna linking to this GitHub page.

**Comment by SimonBiggs** [comment]
Really want to be able to link to this... Imma going to do a force merge on this one.

**Comment by Centrus007** [comment]
No worries :)

**Comment by Centrus007** [comment]
Very cool, btw!

**Comment by Centrus007** [comment]
@SimonBiggs, it's a small thing, but can the package graphs be sorted higher than the module graphs? I.e. in an order of:

`pymedphys` (big cahuna)
`pymedphys_analysis` (package)
`pymedphys_analysis.gamma` (module)

rather than:

`pymedphys` (big cahuna)
`pymedphys_analysis.gamma` (module)
`pymedphys_analysis` (package)

**Comment by SimonBiggs** [comment]
> @SimonBiggs, it's a small thing, but can the package graphs be sorted higher than the module graphs? I.e. in an order of:
> 
> `pymedphys` (big cahuna)
> `pymedphys_analysis` (package)
> `pymedphys_analysis.gamma` (module)
> 
> rather than:
> 
> `pymedphys` (big cahuna)
> `pymedphys_analysis.gamma` (module)
> `pymedphys_analysis` (package)

Certainly can.

The key is in the following line of code if you're able to make the adjustment. Otherwise I can get to it soonish:

https://github.com/pymedphys/pymedphys/blob/f4d404fa1cf3f551c4aa80ef27438f418c61a436/packages/pymedphys_monomanage/src/pymedphys_monomanage/draw/docs.py#L15

**Pull request merged**
