### PR TITLE
[WIP] Medical Physics Workshop

### PR DESCRIPTION
**Pull request by SimonBiggs**
@Centrus007 @sunyu0410

Alright, take 2 (or is it take 3)...

I have removed the pre-reading and instead I think it is worthwhile instead including a link to https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/Index.ipynb

This branch is building its docs at https://pymedphys.com/en/medical-physics-workshop/projects/workshops/2019-acpsem-ml/index.html

My thought process was to have the problems, and examples, all provided as Jupyter Notebooks.

### CODE REVIEW

**Comment by SimonBiggs** [comment]
@Centrus007 do you think a good home for it is in the docs?

**Comment by SimonBiggs** [comment]
Also, @Centrus007 what do you think about the following for demonstrating testing within the docs and examples?

https://github.com/chmp/ipytest

**Comment by Centrus007** [comment]
> do you think a good home for it is having it self contained within the docs?
A good home for what in particular, sorry?

> what do you think about the following for demonstrating testing within the docs and examples?

My bias coming through here, but I just don't really like iPython / Jupyter Notebooks for tutorials... it gets students too comfortable in a non-standard environment. If they take what they've learned and try to apply it in their department in order to create, say, TPS scripts or simple standalone python scripts, they are not really going to be able to do so in something like iPython / JN. They need a standard python installation, and to be comfortable working with one.

I admit "need" is a little strong. But deploying python (especially TPS) scripts as jupyter notebooks is inconvenient, to say the least.

**Comment by Centrus007** [comment]
They're very useful to run experiments and explore functions, perhaps. And that has a very strong place in a tute. But if our aim is to get them to write useful scripts through a step-wise introduction of useful concepts, notebooks as a complication in the form of translating from notebook to script.

**Comment by Centrus007** [comment]
(I'm very open to having my mind changed)

**Comment by SimonBiggs** [comment]
Before you wrote a thing, this morning I woke up and had essentially decided that we can't use notebooks in the tutes. Perfectly okay to link to collaborate for reference material and have people playing with code in their browser before they come... But when they are there, we need to have them set up with VS Code and pytest.

...it really is what we need.

**Comment by SimonBiggs** [comment]
> > do you think a good home for it is having it self contained within the docs?
> A good home for what in particular, sorry?

The problem description and examples. I am leaning away from this also. I think descriptions yes, but for the code, we can actually link to python files stored on GitHub. Get them comfortable with that sort of thing...

**Comment by Centrus007** [comment]
> ...it really is what we need.

👍 


> The problem description and examples. I am leaning away from this also. I think descriptions yes, but 

> for the code, we can actually link to python files stored on GitHub. Get them comfortable with that sort of thing...

👍
 
> Maybe it would be a good idea to have a "workshops" module, where examples for each of the problems are housed in self contained files. And then also have a workshop tests section.

👍

> Use the workshop documentation to create links to all of the required files.

👍


👍
👍
👍
👍
👍
👍
👍
👍
👍
👍
👍
👍
👍
👍
👍
👍
👍

**Comment by SimonBiggs** [comment]
Awesome :)

**Comment by Centrus007** [comment]
Is the USyd link broken for you, too?

http://www.physics.usyd.edu.au/medical-physics/

**Comment by SimonBiggs** [comment]
Yup, it is now. Wasn't yesterday.

**Comment by SimonBiggs** [comment]
@sunyu0410 is Annette able to make a GitHub account and discuss things here instead of emails? It would be nice to be able to have all the discussion in one easy place to reference :).

**Comment by sunyu0410** [comment]
She doesn't have a GitHub account as far as I know.

**Comment by sunyu0410** [comment]
> @sunyu0410 is Annette able to make a GitHub account and discuss things here instead of emails? It would be nice to be able to have all the discussion in one easy place to reference :).

She doesn't have a GitHub account as far as I know.

**Comment by SimonBiggs** [comment]
Will work on this in another branch.

**Pull request closed without merging**
