### PR TITLE
removed app host/web server file system based operations

### PR DESCRIPTION
**Pull request by sjswerdloff**
streamlit.io hosted app was failing due to attempt to operate on file system
branch name is a bit misleading (it's in the code itself, not the test... insufficient coffee while branching)

### CODE REVIEW

**Review by SimonBiggs — APPROVED** [review]
Beautiful :) thanks @sjswerdloff. Merge when you're ready.

**Comment by SimonBiggs** [comment]
No need to wait for codeql to merge, also, the netlify errors are fixed within the main branch.

**Comment by sjswerdloff** [comment]
Waiting on LGTM analysis: Python
Will merge as soon as that completes successfully (and I return from walking the dogs)

**Comment by SimonBiggs** [comment]
Moment of truth :)

https://share.streamlit.io/pymedphys/pymedphys/main/app.py

**Pull request merged**
