### PR TITLE
0.40.0 release prep

### PR DESCRIPTION
**Pull request by Matthew-Jennings**
See list of merged PRs since last release [here](https://github.com/pymedphys/pymedphys/pulls?q=is%3Apr+is%3Amerged).

I'm not sure about how/whether to include some of them in the CHANGELOG:
-  @mguerrajordao, could you please update the dummy CHANGELOG entry I added [here](https://github.com/pymedphys/pymedphys/blob/c446267d34d1cdfbde8c94442459175dbd07b586/CHANGELOG.md?plain=1#L21) for #1773? Or, since it doesn't look like @mguerrajordao has been active since Dec 2022, perhaps @SimonBiggs or @sjswerdloff as the reviewers wouldn't mind updating?
- There were a few (developer facing?) changes that I wasn't sure were worth including. Could I please get a second opinion on whether it's worth adding entries for the following PRs? I'm happy to add entries myself, just not sure on inclusion criteria.
  - #1790
  - #1795
  - #1806
  - #1807
  - #1818 

Cheers,
Matt

### CODE REVIEW

**Review by SimonBiggs — APPROVED** [review]

**Comment by sjswerdloff** [comment]
If we merge in #1827, I will update the ChangeLog to reference that if desired (additional linac state code for TRF).
But I think the ChangeLog wording covers the TRF changes sufficiently as it is.

**Review by sjswerdloff — APPROVED** [review]
LGTM

**Comment by sjswerdloff** [comment]
@Matthew-Jennings please feel free to revert the changelog edit I made.
But the commit served its purpose.  Other than pyright, the tests are coming up clean.

**Comment by sjswerdloff** [comment]
hmmm.  the problem with cypress may be a real thing.
streamlit has updated, and it has what appear to be some breaking changes, and some warnings about calls being made that will be obsolete as of mid April.  So...  not sure where to go with this, @SimonBiggs I think you may need to look at this.

**Comment by SimonBiggs** [comment]
As a first pass we may be able to do an upper pin on streamlit to have the tests pass?

**Comment by sjswerdloff** [comment]
Pinning streamlit below 1.32 doesn't seem to have resolved the issue.
I think we can either iterate down (try 1.31, then 1.30) or just pin at the last known good version of 1.29.
If pinning streamlit at 1.29 doesn't work, we will need to look at the differences in the lock file.
It might have something to do with Electron itself.

**Pull request merged**
