### PR TITLE
Test poetry check when fix is needed and fix Github Actions warning

### PR DESCRIPTION
**Pull request by Matthew-Jennings**
For the latter point:

- CI warning: https://github.com/pymedphys/pymedphys/actions/runs/7626765235/job/20773909487?pr=1820#step:27:10
- Article: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### CODE REVIEW

**Comment by Matthew-Jennings** [comment]
Hi @SimonBiggs, I think this might be close, but the workflow step to push any fixed pre-commit issues is failing an authentication check (see [here](https://github.com/pymedphys/pymedphys/actions/runs/8338518431/job/22818958499?pr=1831#step:7:12)). How is this achieved?

**Comment by SimonBiggs** [comment]
Do the instructions on the GitHub actions readme page help?

https://github.com/ad-m/github-push-action

**Comment by Matthew-Jennings** [comment]
Thanks, I believe it will. Though I think I'll may need access to `pymedphys`' settings to progress with this: 
image

**Comment by SimonBiggs** [comment]
How about now? 😊

**Comment by Matthew-Jennings** [comment]
Okay, I think this is ready. A few points to help:

1. I further tested @nlambriICH's `poetry check` change to confirm the CI fails when `poetry check` is run with an inconsistency between `pyproject.toml` and `poetry.lock
2. I noticed a warning in the CI of a forthcoming deprecation of `set_output` ([see CI](https://github.com/pymedphys/pymedphys/actions/runs/7626765235/job/20773909487?pr=1820#step:27:10)). I've rectified these in accordance with [this](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
3. I added the `poetry-check` pre-commit hook. I've confirmed that it works locally.
   - In the process of adding the hook, I updated our other pre-commit hooks. One thing to note is that `black` has changed the way it reformats long lines. This is the reason for most of the changes in `lib/pymedphys`
4. This same pre-commit hook appears to be working okay in the CI, though it looks like the CI doesn't restart on the new commit if the PR is in draft (is this deliberate?)
4. Use of the PYMEDPHYS_BOT_TOKEN to authenticate a git push didn't work (maybe it hasn't been used in a while and then credentials expired?). In any case, rather than replacing it with a new token, I've replaced it with GITHUB_TOKEN. [This appears to be the recommended means of authenticating in GitHub Actions](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#authenticating-to-the-api-in-a-github-actions-workflow), but I there may have been a good reason to use PYMEDPHYS_BOT_TOKEN

**Comment by Matthew-Jennings** [comment]
Scratch that, looks like the ` >> $GITHUB_OUTPUT` approach is still not working for PyMedPhys Cache :(

**Comment by Matthew-Jennings** [comment]
Okay, `>> $GITHUB_OUTPUT`s appear to be working. Last outstanding thing is how to trigger the CI again after the CI pushes new changes after pre-commit fixes. Really not sure how to proceed here...

**Comment by SimonBiggs** [comment]
When I ask Claude Pro your question I get this response:

How can I retrigger CI in GitHub actions?

In GitHub Actions, you can retrigger a CI workflow using the workflow_dispatch event. This event allows you to manually trigger a workflow run using the GitHub API or through the GitHub web interface.

Here's how you can set up a workflow to be triggered manually and retrigger itself:

Create a new workflow file (e.g., .github/workflows/retrigger.yml) in your repository.
In the workflow file, define the workflow_dispatch event as a trigger:
yaml


Copy code
on:
  workflow_dispatch:
Define the desired jobs and steps in your workflow. For example:
yaml


Copy code
jobs:
  retrigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your pre-commit fixes and other steps here

      - name: Push changes
        run: |
          git config user.email "github-actions@example.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Automated fixes"
          git push
To retrigger the workflow after pushing the changes, you can make an API call to the GitHub Actions API to trigger the workflow again. Here's an example using curl:
yaml


Copy code
      - name: Retrigger workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/retrigger.yml/dispatches \
            -d '{"ref": "main"}'
Make sure to replace main with the appropriate branch name if needed.

Commit and push the workflow file to your repository.
Now, whenever you want to manually trigger the workflow and have it retrigger itself after pushing changes, you can do so using one of the following methods:

Through the GitHub web interface:
Go to the "Actions" tab in your repository.
Select the workflow you created.
Click on the "Run workflow" button and choose the branch to run it on.
Using the GitHub API:
Make a POST request to the workflow dispatch API endpoint:

Copy code
POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
Replace {owner}, {repo}, and {workflow_id} with the appropriate values.
Include an authorization token in the request headers.
Please note that the GITHUB_TOKEN used in the example has some limitations. It may not have sufficient permissions to trigger workflows in certain scenarios, such as in forked repositories. If you encounter permission issues, you may need to create a personal access token with the necessary permissions and use it instead.

Remember to be cautious when setting up retriggering workflows to avoid unintended infinite loops. Make sure to include appropriate conditions and checks to prevent endless CI runs.

**Comment by Matthew-Jennings** [comment]
@SimonBiggs, so it wasn't working before? That is the main reason I asked for help: your unique experience/history with the `pymedphys` workflow.

Similarly, there is no reason to keep using PYMEDPHYS_BOT_TOKEN? It was you who made that change in the workflow.

**Comment by SimonBiggs** [comment]
It was working before, but not any longer it seems. I don't mind it being done in a new way... As long as it works right?

**Comment by Matthew-Jennings** [comment]
My switch to `GITHUB_TOKEN` appears to be the problem -> it doesn't have permissions to trigger a new workflow. This is likely the reason for using `PYMEDPHYS_BOT_TOKEN`.

`PYMEDPHYS_BOT_TOKEN` appears to be an access token created for a GitHub user [`pymedphys-bot`](https://github.com/pymedphys-bot).

I think there are three solutions:

1. Continue using `PYMEDPHYS_BOT_TOKEN`. I think we'll need its GitHub login credentials to create a new access token. If you prefer this, @SimonBiggs, can you do this (or securely provide the login credentials)?
2. Try to make GITHUB_TOKEN work with `workflow_dispatch`. This looks complicated, but happy to give it a try.
3. (My suggestion) Register a GitHub App (e.g. `pymedphys-ci-bot`). See [here](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow#authenticating-with-a-github-app). This allows for nicely tailored permissions, and can be created/maintained in the PyMedPhys org. If we go this route, either I'll need elevated access to the org (right now I cannot access the org settings), or you'll need to create/config the App, @SimonBiggs.

**Comment by SimonBiggs** [comment]
The GitHub app approach sounds awesome. I'll give y'all org admin :)

**Comment by SimonBiggs** [comment]
Done, all maintainers, including yourself @Matthew-Jennings are now owner of the PyMedPhys org

**Comment by SimonBiggs** [comment]
Also, if we do end up having a few GitHub apps, I'd be more than happy to donate my personal Anthropic API token (not company associated, but my own account) to the PyMedPhys org, which will allow us to set up a "Claude issues bot" GitHub action.

The first pass could just allow us to call @Claude in an issue, and it will then respond directly within the GitHub issue to provide help to the user.

Second and third passes could allow us to also include the PyMedPhys code / GitHub PR content and then have Claude help us with code reviews and the like 🙂

**Comment by Matthew-Jennings** [comment]
> Also, if we do end up having a few GitHub apps, I'd be more than happy to donate my personal Anthropic API token (not company associated, but my own account) to the PyMedPhys org, which will allow us to set up a "Claude issues bot" GitHub action.
> 
> The first pass could just allow us to call Claude in an issue, and it will then respond directly within the GitHub issue to provide help to the user.
> 
> Second and third passes could allow us to also include the PyMedPhys code / GitHub PR content and then have Claude help us with first passes on code reviews and the like 🙂

Sounds awesome to me! I'm quite keen to dive into this.

**Comment by Matthew-Jennings** [comment]
Finally, I think we're in business!

**Comment by Matthew-Jennings** [comment]
Perhaps we should merge #1820 first?

**Comment by SimonBiggs** [comment]
> I'm quite keen to dive into this

I'll add an Anthropic API key as an org secret now so that you're free to get started whenever it works best for you.

**Comment by SimonBiggs** [comment]
API key now added here:
https://github.com/organizations/pymedphys/settings/secrets/actions

**Review by SimonBiggs — APPROVED** [review]
Lgtm :)

**Pull request merged**
