### PR TITLE
Update test_anonymise.py

### PR DESCRIPTION
**Pull request by Matthew-Jennings**

### CODE REVIEW

**Comment by SimonBiggs** [comment]
No luck? I can try get to the bottom of it tonight if it's not working for you...

**Comment by Matthew-Jennings** [comment]
> No luck? I can try get to the bottom of it tonight if it's not working for you...

Not yet. It’s quite a puzzler, and I’m very limited in my tools/equipment at the moment :(

**Comment by Matthew-Jennings** [comment]
I think that’s done it! A doc issue related to @phchlap’s new notebook appears the be a remaining issue

**Comment by Matthew-Jennings** [comment]
Stuffed up Git workflow (bugger working on an iPad!)

**Pull request closed without merging**
