### PR TITLE
parse using pydicom.valuerep.DT

### PR DESCRIPTION
**Pull request by sjswerdloff**
combine with tzinfo from passed in value even if None to ensure operating on datetime.datetime objects
DT has problems with addition of timedelta or at least it did in initial testing.

See #1246

### CODE REVIEW

**Review by SimonBiggs — APPROVED** [review]
LGTM 🙂 

Were you interested in getting these bugfixes released sooner rather than later?

An option that shouldn't be too hard would be to make a dev release for trialing within onkodicom?

Release process for a dev release is as follows:

```
# Step 1: edit version number in pyproject.toml only

# 2 - 4:
poetry run pymedphys dev propagate

poetry build
poetry deploy
```

**Comment by sjswerdloff** [comment]
I have started looking at hypothesise, but it will take some further analysis on my part to see if it's actually useful for my purposes.  I need to generate DICOM conformant values for each of the VR and iterate against the methods for each VR with the variety of values generated.  It's kind of like fuzzying the input, but in a very constrained fashion.

**Comment by sjswerdloff** [comment]
> LGTM 🙂
> 
> Were you interested in getting these bugfixes released sooner rather than later?
> 
> An option that shouldn't be too hard would be to make a dev release for trialing within onkodicom?
> 
> Release process for a dev release is as follows:
> 
> ```
> # Step 1: edit version number in pyproject.toml only
> 
> # 2 - 4:
> poetry run pymedphys dev propagate
> 
> poetry build
> poetry deploy
> ```

Yes.  I'll get started on it...
I'll ask for help if I bump in to problems...

**Comment by sjswerdloff** [comment]
@SimonBiggs 
when I type in
`poetry deploy`
I get:

`The command "deploy" is not defined.`

should I be using 
`poetry publish`

**Comment by SimonBiggs** [comment]
Yup, publish, that's the one. Sorry got confused with yarn's (?) CLI.

**Pull request merged**
