### PR TITLE
Document pseudonymisation in cli

### PR DESCRIPTION
**Pull request by sjswerdloff**
Sorry, but I have no background in .rst
Look forward to corrections and reading material...

### CODE REVIEW

**Comment by SimonBiggs** [comment]
Running

```
pymedphys dev docs
```

Will build the docs locally, if that helps :).

**Comment by sjswerdloff** [comment]
> Running
> 
> ```
> pymedphys dev docs
> ```
> 
> Will build the docs locally, if that helps :).

If I run the command line exactly as specified I get
Application error:
config directory doesn't contain a conf.py file (/home/osboxes/anaconda3/envs/pymedphys3/lib/python3.7/site-packages/docs)

If I instead run 
poetry run pymedphys dev docs
I get
Running Sphinx v3.2.0

Extension error:
Could not import extension sphinxcontrib.napoleon (exception: No module named 'sphinxcontrib.napoleon')

and if I try to do 
pip install sphinxcontrib-napoloean
I get
ERROR: Could not find a version that satisfies the requirement sphinxcontrib-napoloean (from versions: none)
ERROR: No matching distribution found for sphinxcontrib-napoloean

**Comment by SimonBiggs** [comment]
If you have a look within the CI pipeline document you can see what the CI is required to do in order to run the docs:

* Install pandoc
https://github.com/pymedphys/pymedphys/blob/c00fea77488e5919c53b475bcd217ba40ea1b5aa/.github/workflows/on-push.yml#L169-L182

* Install pymedphys, with poetry, but make sure to include the `-E docs` flag
https://github.com/pymedphys/pymedphys/blob/c00fea77488e5919c53b475bcd217ba40ea1b5aa/.github/workflows/on-push.yml#L192-L197

* Then build the docs
https://github.com/pymedphys/pymedphys/blob/c00fea77488e5919c53b475bcd217ba40ea1b5aa/.github/workflows/on-push.yml#L271-L276

Importantly, the reason you're getting that error message is that you don't have some of the docs dependencies installed. So you need to run `poetry install -E docs`.

If you're interested, that will run off and install the following libraries:

https://github.com/pymedphys/pymedphys/blob/c00fea77488e5919c53b475bcd217ba40ea1b5aa/pyproject.toml#L119-L123

**Comment by SimonBiggs** [comment]
Regarding the sphinx pinning, you can see the following file where all those pins are defined:

https://github.com/pymedphys/pymedphys/blob/c00fea77488e5919c53b475bcd217ba40ea1b5aa/pyproject.toml#L86-L95

Installing the appropriate versions though will all be handled for you when you run `poetry install -E docs`

**Comment by sjswerdloff** [comment]
The (ubuntu,tests) error is something I saw previously, went back and forth on how to get the name equivalent of the SOP Class, and then "it worked" (with the code as it is currently).  But I didn't change the code in this PR.
The (ubuntu,docs) error is something I can fiddle with and see what happens on commits (given I am having problems with running Sphinx and friends in my own environment).

**Comment by sjswerdloff** [comment]
doing the 
poetry install --no-dev -E docs 
appears to have borked my environment (basic regression tests failing to find things related to something called pytz, which is listing in conda and pip).

I'll re-install everything from scratch, tomorrow.

**Comment by SimonBiggs** [comment]
> doing the
> poetry install --no-dev -E docs
> appears to have borked my environment (basic regression tests failing to find things related to something called pytz, which is listing in conda and pip).
> 
> I'll re-install everything from scratch, tomorrow.

Importantly, you are in a dev environment, you want to run:

```
poetry install -E docs
```

not

```
poetry install --no-dev -E docs
```

**Comment by SimonBiggs** [comment]
> appears to have borked my environment (basic regression tests failing to find things related to something called pytz, which is listing in conda and pip).

I'm confused as to how this is related to conda....

**Comment by sjswerdloff** [comment]
conda is the baseline environment I start with, pip and conda don't always list exactly the same information.
But... I've re-installed from scratch following the linux-contributor guidelines, followed with 
poetry install -E docs
and voila, 
pymedphys dev docs
works perfectly.

**Comment by SimonBiggs** [comment]
> conda is the baseline environment I start with, pip and conda don't always list exactly the same information.
> But... I've re-installed from scratch following the linux-contributor guidelines, followed with
> poetry install -E docs
> and voila,
> pymedphys dev docs
> works perfectly.

kk, probably best to run `poetry run pymedphys dev docs` anyway, because then it is explicitly using your poetry environment. Whenever there is a `pymedphys` command, always prepend it with `poetry run` if you want to use the version within git. Otherwise it'll run off and use an installed version of pymedphys instead.

**Comment by sjswerdloff** [comment]
fyi, after re-installation, I had to run 
poetry install -E tests
to get the testing to work.

**Comment by sjswerdloff** [comment]
> Whenever there is a pymedphys command, always prepend it with poetry run if you want to use the version within git.
Yup, did that.

**Comment by SimonBiggs** [comment]
> fyi, after re-installation, I had to run
> poetry install -E tests
> to get the testing to work.

Yup, to start a dev environment you'll want to run `poetry install -E tests -E docs`

**Comment by sjswerdloff** [comment]
The failing updates test is the same streamlit issue as elsewhere, not related to this PR

**Pull request merged**
