### PR TITLE
Update the Electron Factors baseline | Fixes cypress CI

### PR DESCRIPTION
**Pull request by SimonBiggs**
This is to fix the Cypress CI

---

Heads up @laser47-hue,

It appears either a recent numpy or scipy update has changed the spline fitting algorithm slightly resulting in differences on the order of ~0.5% within the electron factor algorithm.

### CODE REVIEW

**Review by Matthew-Jennings — COMMENTED** [review]
It feels to me like this one probably requires a decent CHANGELOG entry. Even though we're changing the baseline, not the code, it's worth noting *somewhere* that different `scipy` versions will give different results here.

For all I know at least, the electron factors code is used clinically, quite possibly by users who are not pinning dependencies...

Also, are both spline implementations in PyMedPhys' permissable `scipy` version range?

**Comment by SimonBiggs** [comment]
> It feels to me like this one probably requires a decent CHANGELOG entry

Yup, that's a good idea. Will fix.

> Also, are both spline implementations in PyMedPhys' permissable `scipy` version range?

I don't know explicitly what caused this change.

**Comment by SimonBiggs** [comment]
Added entry to changelog, added a loud warning that raises on algo use, and created a GitHub issue for users to report their deviations.

**Review by Matthew-Jennings — APPROVED** [review]
LGTM.

**Pull request merged**
