### PR TITLE
Pinnacle export fixes

### PR DESCRIPTION
**Pull request by pchlap**
Just a minor fix so that this tool can handle when an image is missing from a tar archive (seems be the case for us when phantom data is used, it is added as a sym link and doesn't get included in the tar archive).

@SimonBiggs Not sure if you want to me to merge changes like this myself or if you want me to assign a reviewer? Since this tool is still completely in labs then probably no review required?

I want to ensure I follow best practice properly, so would I update the change log for this? This change would then get rolled out with the next update, is that right? 0.31.0?

### CODE REVIEW

**Comment by SimonBiggs** [comment]
> @SimonBiggs Not sure if you want to me to merge changes like this myself or if you want me to assign a reviewer? Since this tool is still completely in labs then probably no review required?

In an ideal world someone else who was using the tool who had an understanding of this part of the code base would review. Unfortunately I'm neither. If there is someone who fits that bill a review would be awesome, but yes, I'm happy to approve this.

> I want to ensure I follow best practice properly, so would I update the change log for this? This change would then get rolled out with the next update, is that right? 0.31.0?

Yup, do update the changelog, just put it under a version number of "unreleased" and I'll write in the version number when forging the release. Once this pull requests lands I'll cut a development release (likely 0.31.0dev1) so that you can install it locally and see how it fairs.

**Comment by pchlap** [comment]
> > @SimonBiggs Not sure if you want to me to merge changes like this myself or if you want me to assign a reviewer? Since this tool is still completely in labs then probably no review required?
> 
> In an ideal world someone else who was using the tool who had an understanding of this part of the code base would review. Unfortunately I'm neither. If there is someone who fits that bill a review would be awesome, but yes, I'm happy to approve this.
> 
> > I want to ensure I follow best practice properly, so would I update the change log for this? This change would then get rolled out with the next update, is that right? 0.31.0?
> 
> Yup, do update the changelog, just put it under a version number of "unreleased" and I'll write in the version number when forging the release. Once this pull requests lands I'll cut a development release (likely 0.31.0dev1) so that you can install it locally and see how it fairs.

Thanks Simon. I have updated the change log. There is a lot that can/should be improved with this code, so when I one day get around to reworking it a proper review would be valuable then.

**Comment by SimonBiggs** [comment]
Thanks Phil,

I'm actually currently in Sydney (drove up today) but I jumped on and made
a dev release. If you install it where you need to test it by running `pip
install pymedphys==0.31.0dev1` that will give you a release that has your
patches included.

I'll merge when I get back to Wagga :) and I can make a production release
at some point next week if everything aligns.

Cheers :),
Simon

**Comment by SimonBiggs** [comment]
Also with code review, the following is a great mantra:

In general, reviewers should favour approving a CL once it is in a state
where it definitely improves the overall code health of the system being
worked on, even if the CL isn't perfect.

-- 
https://github.com/google/eng-practices/blob/master/review/reviewer/standard.md

On that point, so that we can take steps towards having this portion of the
code base better tested, would you be in a position to submit a data
example that previously failed on the prior code, but now works on the
current changes? That would be a great way to incrementally step this part
of the code base to having more rigorous testing.

Data files can be uploaded to Zenodo (
https://zenodo.org/deposit/new?c=pymedphys) and then the url added to
https://github.com/pymedphys/pymedphys/blob/master/pymedphys/_data/urls.json
then that data can be utilised in a test much like the following:

https://github.com/pymedphys/pymedphys/blob/91fda2bd34487bcc4700453b8dc7a4a35de27bc4/pymedphys/tests/dicom/test_structure_dedupe.py#L28

That test simply takes a "baseline" result file (what the output should be)
as well as an input file:

https://zenodo.org/record/3828058#.Xuti_GR_V-E

If that was possible for this pull request that would be awesome, and then,
if that test passes and before it failed, then it most certainly meets that
requirement given above, "definitely improves the overall code health of
the system being worked on".

That would be awesome Phil :).

**Comment by SimonBiggs** [comment]
Also, to further push for the testing, if any of your tests use pydicom you can add a "pydicom" mark to them and they will also be run for every upstream merge that happens within pydicom as of the following pull request that landed today:

https://github.com/pydicom/pydicom/pull/1129#event-3455626870

My thought is to be able to do the same with pylinac also and essentially build an early alert system for developers if any changes in pudicom, pylinac, or pymedphys break their code.

**Comment by pchlap** [comment]
Thanks a heap Simon, I will try to put together a test case which failed and will now pass later today.

> Also, to further push for the testing, if any of your tests use pydicom you can add a "pydicom" mark to them and they will also be run for every upstream merge that happens within pydicom as of the following pull request that landed today:
> 
> [pydicom/pydicom#1129 (comment)](https://github.com/pydicom/pydicom/pull/1129#event-3455626870)
> 
> My thought is to be able to do the same with pylinac also and essentially build an early alert system for developers if any changes due to be released in an up coming pydicom, pylinac, or pymedphys break their code.

This is super cool, I think you must have already marked the Pinnacle export tests with pydicom, most of them already had it. I love the concept of an early alert system for upcoming changes.

**Comment by SimonBiggs** [comment]
Also "e2e black box testing" which is what I proposed is an easy test type but they can sometimes cause false alarms if something in the code changes the result but that doesn't mean a failure. Can be quite painful to maintain when they do fail, and can result in code being frozen when it really should be able to be more flexible and still meet its requirements.

So, if you feel like implementing a different test type, for example creating a dummy file from code that focuses only on the issue in question, and then tests that to an expected output that has been crafted with code. The dummy file doesn't have to be valid, in fact it can often be far simpler if the dummy file only contains the very thing being tested, and nothing else. An example of that test type can be seen in the following:

https://github.com/pymedphys/pymedphys/blob/91fda2bd34487bcc4700453b8dc7a4a35de27bc4/pymedphys/tests/dicom/test_header_tweaks.py#L61-L82

**Comment by SimonBiggs** [comment]
Don't stress about the "updates" test failing. That just signifies that one of our dependencies updating has caused a fail, not the code changes here. Thanks for this @pchlap!

If you're keen for a release to get out soon I can prioritise a release if you'd like?

**Comment by pchlap** [comment]
> Don't stress about the "updates" test failing. That just signifies that one of our dependencies updating has caused a fail, not the code changes here. Thanks for this @pchlap!
> 
> If you're keen for a release to get out soon I can prioritise a release if you'd like?

Ah ok, cool no worries. No need to prioritise a release for this I don't think. Since no one has complained about this I think I am the only one experiencing this issue. And I can use the pre-release version until it rolls out in the next update :)

Thanks Simon!

**Comment by SimonBiggs** [comment]
LGTM, I'm happy to have this merged :). I've just approved it. You should be able to do the merge yourself.

Cheers,
Simon

**Comment by pchlap** [comment]
> LGTM

Thanks Simon!

**Pull request merged**
