### PR TITLE
[RFR] Sweep out the old to prep for the new

### PR DESCRIPTION
**Pull request by SimonBiggs**

### CODE REVIEW

**Comment by SimonBiggs** [comment]
Certainly quite a bit of work here stripping out the old deprecated tools that the readthedocs theme is built with...

Anyway, getting there. I have currently broken the javascript, but should be able to fix that...

**Comment by SimonBiggs** [comment]
@Centrus007 so, javascript is now back up and running! :)

https://deploy-preview-245--pymedphys.netlify.com/

...it might not look like much from the front, but the whole suite of 4-6 year old unmaintained dependencies (incompatible with most of today's stuff) that the readthedocs theme was built upon have been swapped out for the latest tooling.

A development server with webpack has been set up which allows us to edit the css and javascript and see the page build and display.

A few more things to do on this branch and then it is ready to merge... in a position to then move forward and begin implementing what we want to implement with it!

**Comment by SimonBiggs** [comment]
@Centrus007 hopefully this should pass. It's ready for review and merge :)

**Comment by Centrus007** [comment]
Not sure how best to review this except for looking through the docs preview thoroughly. Noticed you're still working on it though?

**Comment by SimonBiggs** [comment]
I'm done with this now :) happy for it to merge :)

**Pull request merged**
