### PR TITLE
Address/fix verification sop class attribute wrt pynetdicom

### PR DESCRIPTION
**Pull request by sjswerdloff**
LBYL with verification sop class attribute to address interface change in pynetdicom 2.0

### CODE REVIEW

**Comment by sjswerdloff** [comment]
I tried 
`poetry run pymedphys --debug dev tests --pylint --pylint-jobs=1`
before committing and pushing upstream, but it failed on almost everything (changing a few lines of code in one file should not result in that).  Did I 'miss a memo' regarding pylint?
I've attached the output from the above command (stdout).  The stderr was brief and uneventful.
[lintout.txt](https://github.com/pymedphys/pymedphys/files/7834051/lintout.txt)

Should I have incremented to dev5 in pyproject.toml ?

**Comment by sjswerdloff** [comment]
I don't understand why the (windows, docs) test is failing.
It says pandoc is failing to install (using chocolatey).
I did a naive installation of pandoc using chocolatey on a Windows machine just now, and other than requiring that I confirm running chocolateyInstall.ps1, that went quite smoothly (pandoc 2.16.2).

**Comment by sjswerdloff** [comment]
I had an extend_ct streamlit app in earlier history that used the verification attribute but it seems to  have disappeared in the most recent main, so there  is  only one place in the code with `pynetdicom.sop_class.VerificationSOPClass` that showed up in my
`grep -r VerificationSOPClass `

**Comment by SimonBiggs** [comment]
Just checking, any reason to not go with the thread-safe alternative of the following?

```python
try:
    verification_sop_class = pynetdicom.Verification
except AttributeError:
    verification_sop_class = pynetdicom.VerificationSOPClass
```

**Comment by SimonBiggs** [comment]
> I tried
> `poetry run pymedphys --debug dev tests --pylint --pylint-jobs=1`
> before committing and pushing upstream, but it failed on almost everything (changing a few lines of code in one file should not result in that). Did I 'miss a memo' regarding pylint?

To run pylint you'll want to run the following command:

https://github.com/pymedphys/pymedphys/blob/a8e8a18116171749fd548e8af2967325f250a312/.github/workflows/library.yml#L417

**Comment by SimonBiggs** [comment]
> I don't understand why the (windows, docs) test is failing.
> It says pandoc is failing to install (using chocolatey).

Yeah, I don't understand either... I just did a 're-run' of the CI to see if that fixes it.

**Comment by SimonBiggs** [comment]
> I had an extend_ct streamlit app in earlier history that used the verification attribute but it seems to have disappeared in the most recent main, 

Yup, the extend_ct app used private Streamlit APIs. If I was still at RCCC I would have been in a position to update the app to handle that private API changing... but... holding onto an app that uses private APIs is too much of a maintenance burden. If someone wants it back I can guide them on how to put in the work to bring it back :slightly_smiling_face:.

> so there is only one place in the code with `pynetdicom.sop_class.VerificationSOPClass` that showed up in my
> `grep -r VerificationSOPClass`

Awesome :slightly_smiling_face:. Thanks @sjswerdloff :slightly_smiling_face:.

**Review by SimonBiggs — APPROVED** [review]
LGTM (just one nit as a comment re LBYL vs EAFP). Feel free to merge as is, or make that change.

Thanks @sjswerdloff for sorting this one out :)

**Comment by sjswerdloff** [comment]
> > I tried
> > `poetry run pymedphys --debug dev tests --pylint --pylint-jobs=1`
> > before committing and pushing upstream, but it failed on almost everything (changing a few lines of code in one file should not result in that). Did I 'miss a memo' regarding pylint?
> 
> To run pylint you'll want to run the following command:
> 
> https://github.com/pymedphys/pymedphys/blob/a8e8a18116171749fd548e8af2967325f250a312/.github/workflows/library.yml#L417

That worked, thank you...  The remaining complaints are about streamlit.columns (in a variety of streamlit related code)

> E1101: Module 'streamlit' has no 'columns' member (no-member)

That appears to be a documented  API, and the version of streamlit is pinned, is there a way to  stop that complaint or fix it short  of peppering with  
`# pylint: disable = no-member`

**Comment by sjswerdloff** [comment]
> LGTM (just one nit as a comment re LBYL vs EAFP). Feel free to merge as is, or make that change.
> 
> Thanks @sjswerdloff for sorting this one out :)

Took the sledgehammer approach (it's a constant in the DICOM Standard, I hardcoded the constant and included the  reference).   That should avoid threading issues, choices between EAFP and LBYL, and any possible change in pynetdicom.
The DICOM Standard is not going to change the SOP Class UID for Verification in any living person's lifetime.

**Comment by SimonBiggs** [comment]
> Took the sledgehammer approach

Sounds good to me :)

**Comment by SimonBiggs** [comment]
> That appears to be a documented API, and the version of streamlit is pinned, is there a way to stop that complaint

I suspect you need to run `poetry install` within your environment. You potentially have an outdated Streamlit version installed locally?

**Pull request merged**
