### PR TITLE
Add Marcus Fisk as an active contributor

### PR DESCRIPTION
**Pull request by laser47-hue**

### CODE REVIEW

**Review by Matthew-Jennings — APPROVED** [review]

**Comment by Matthew-Jennings** [comment]
LGTM. Merge when happy.

**Comment by SimonBiggs** [comment]
Woo hoo :) welcome Marcus :).

Might you be able to scale the logo down to 200x200px and include it with the other logos in the active contributors section?

**Comment by laser47-hue** [comment]
@SimonBiggs, thanks I've just updated the README now!

**Review by SimonBiggs — APPROVED** [review]
Beautiful :)

**Pull request merged**
