### PR TITLE
[RFR] 0.6.x

### PR DESCRIPTION
**Pull request by SimonBiggs**

### CODE REVIEW

**Comment by Centrus007** [comment]
Just having a squiz at [this diff](https://github.com/pymedphys/pymedphys/compare/v0.5.1..v0.6.0) to see what we missed in [changelog.md](https://github.com/pymedphys/pymedphys/blob/0.6.x/changelog.md) (I know I keep forgetting...)

**Comment by SimonBiggs** [comment]
That is one super diff...

**Comment by SimonBiggs** [comment]
...makes me want to release more regularly...

**Comment by Centrus007** [comment]
Is it worth adding the following to changelog (and docs)?

- new CLIs: [src/pymedphys/cli/main.py](https://github.com/pymedphys/pymedphys/blob/0c5b74b33cddf6792bed13ab7eeb522d48eac4eb/src/pymedphys/cli/main.py)
- coordinates transforms: [src/pymedphys/coordinates/_level1/coordinatestransforms.py](https://github.com/pymedphys/pymedphys/blob/0c5b74b33cddf6792bed13ab7eeb522d48eac4eb/src/pymedphys/coordinates/_level1/coordinatestransforms.py)
- dicom creation functions: [src/pymedphys/dicom/_level1/dicom_create.py](https://github.com/pymedphys/pymedphys/blob/0c5b74b33cddf6792bed13ab7eeb522d48eac4eb/src/pymedphys/dicom/_level1/dicom_create.py)
- Code moved to `dcm_struct`? (not breaking, I don't think): [src/pymedphys/dicom/_level1/dicom_struct.py](https://github.com/pymedphys/pymedphys/blob/0c5b74b33cddf6792bed13ab7eeb522d48eac4eb/src/pymedphys/dicom/_level1/dicom_struct.py)
- Improved dicom anonymisation (dummy values): [src/pymedphys/dicom/_level2/dicom_anonymise.py](https://github.com/pymedphys/pymedphys/blob/0c5b74b33cddf6792bed13ab7eeb522d48eac4eb/src/pymedphys/dicom/_level2/dicom_anonymise.py)
- New DicomDose class and reversion from `namedtuple` to `tuple` for coord extraction functions: [src/pymedphys/dicom/_level2/dicom_dose.py](https://github.com/pymedphys/pymedphys/blob/0c5b74b33cddf6792bed13ab7eeb522d48eac4eb/src/pymedphys/dicom/_level2/dicom_dose.py)
- DICOM header tweaking: [src/pymedphys/dicom/_level2/header_tweaks.py](https://github.com/pymedphys/pymedphys/blob/0c5b74b33cddf6792bed13ab7eeb522d48eac4eb/src/pymedphys/dicom/_level2/header_tweaks.py)
- small adjustments to gamma (e.g. renaming of `convert_to_percent_pass()` to `calculate_pass_rate()`: [src/pymedphys/gamma/_level1/gammafilter.py](https://github.com/pymedphys/pymedphys/blob/0c5b74b33cddf6792bed13ab7eeb522d48eac4eb/src/pymedphys/gamma/_level1/gammafilter.py)
- The xlwings stuff
- Any new logfile analysis or mudensity stuff (bit hard for me to tell if it's new or just refactored)

**Comment by Centrus007** [comment]
I can at least handle the coordinates transforms, dicom anonymisation and dicom dose changes. Can help with others as or if needed

**Comment by Centrus007** [comment]
coordinates transforms will need docs entry. Maybe they can be skipped from the Changelog for now?

**Comment by SimonBiggs** [comment]
I think we certainly could add those to the changelogs, and have those
changes to the docs. We'll have to release a 0.6.1 to have those items
appear in the docs, but that's no biggy.

**Comment by SimonBiggs** [comment]
Certainly at least have them on the changelogs. Add to the docs what you
believe is worthwhile.

**Comment by Centrus007** [comment]
How's that?

I left out any mention of the new `DicomDose` class. It's not ready and completely unused so far.

**Comment by SimonBiggs** [comment]
KK, shall we merge this and maybe I'll just try and delete the v0.6.0 tag and point it to the latest commit.

**Comment by Centrus007** [comment]
Yep, no wukkas. What is it that you do precisely when you cut a release? I'm thinking we tag only *immediately* prior to whatever that is...

**Comment by Centrus007** [comment]
Crap, just realised I deleted the branch.

Probably okay for the 0.x releases, but would you want to maintain all x.y release branches for patching older versions?

**Comment by SimonBiggs** [comment]
I think it can still be restored? I have read the docs pointing to the 0.6.x branch already as an option

**Comment by SimonBiggs** [comment]
I don't think we completely narrowed in on a best method for release branches.

Best to sort out what we should be doing before 1.0.0 though :).

**Comment by SimonBiggs** [comment]
So, stable now has the new changelog:

http://pymedphys.com/en/stable/additional/changelog.html#id3

And latest pypi is 0.6.0:

https://pypi.org/project/pymedphys/

Still having a few issues getting conda to play ball, but getting there:

https://github.com/conda-forge/pymedphys-feedstock/pull/9

**Pull request merged**
